/**
 * Fix the final 15 words in advanced.ts that still lack examples.
 * These were generated by the API but the file write failed due to a code bug.
 */
import * as fs from 'fs';
import * as path from 'path';

const WORD_DATA_DIR = path.resolve(import.meta.dirname || path.dirname(new URL(import.meta.url).pathname), '../src/data/wordbank/data');
const API_ENDPOINT = 'https://api.deepseek.com/v1/chat/completions';
const MODEL = 'deepseek-chat';

function getApiKey(): string {
  try { return fs.readFileSync(new URL('.apikey', import.meta.url).pathname, 'utf-8').trim(); } catch { return ''; }
}

function extractWords(filePath: string): { varName: string; words: any[] } | null {
  const content = fs.readFileSync(filePath, 'utf-8');
  const varMatch = content.match(/export const (\w+): IWordEntry\[\] = (\[[\s\S]*\]);?\s*$/);
  if (!varMatch) return null;
  try { return { varName: varMatch[1], words: new Function(`return ${varMatch[2]}`)() }; }
  catch (e) { return null; }
}

function formatWordEntry(w: any): string {
  return [
    `  {word:${JSON.stringify(w.word)},`,
    `phonetic:${JSON.stringify(w.phonetic)},`,
    `partOfSpeech:${JSON.stringify(w.partOfSpeech)},`,
    `meaning:${JSON.stringify(w.meaning)},`,
    `level:${JSON.stringify(w.level)},`,
    `frequencyRank:${w.frequencyRank},`,
    `collocations:${JSON.stringify(w.collocations)},`,
    `examples:${JSON.stringify(w.examples)},`,
    `synonyms:${JSON.stringify(w.synonyms)},`,
    `antonyms:${JSON.stringify(w.antonyms)},`,
    `wordFamily:${JSON.stringify(w.wordFamily)},`,
    `register:${JSON.stringify(w.register)},`,
    `emotion:${JSON.stringify(w.emotion)},`,
    `topics:${JSON.stringify(w.topics)},`,
    `hasNoChineseEquivalent:${w.hasNoChineseEquivalent},`,
    `deepExplanation:${JSON.stringify(w.deepExplanation)}},`,
  ].join('');
}

function writeFile(filePath: string, varName: string, words: any[]): void {
  const header = [
    `// ${varName.replace('_WORDS', '').replace('_', ' ')} wordbank — ${words.length} words`,
    `// Data source: KyleBing/english-vocabulary (MIT license)`,
    `// Generated independently: may include words also found in lower levels`,
    `import type { IWordEntry } from '../schema';`,
    ``,
    `export const ${varName}: IWordEntry[] = [`,
  ].join('\n');
  const entries = words.map(formatWordEntry);
  const output = header + '\n' + entries.join('\n') + '\n];\n';
  fs.writeFileSync(filePath, output, 'utf-8');
}

async function generateForWords(missingWords: any[]): Promise<Map<string, { en: string; zh: string }[]>> {
  const wordList = missingWords.map(w =>
    `"${w.word}" (${w.partOfSpeech}): ${w.meaning.split('；')[0].split(';')[0]}`
  ).join('\n');

  const prompt = `For each of the following English words, create 1-2 natural, authentic example sentences with Chinese translations.

Requirements:
- Sentences should be natural and commonly used by native English speakers
- Use the word naturally in context - do NOT write "An example with X"
- Chinese translations should be accurate and natural
- Output as a JSON array: [{"word": "theword", "examples": [{"en": "English sentence.", "zh": "中文翻译。"}]}]

Words:
${wordList}

Respond ONLY with the valid JSON array, no other text.`;

  const apiKey = getApiKey();
  const response = await fetch(API_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({ model: MODEL, messages: [
      { role: 'system', content: 'You are a professional English lexicographer. Create high-quality example sentences.' },
      { role: 'user', content: prompt },
    ], max_tokens: 4096, temperature: 0.7 }),
  });

  const data = await response.json() as any;
  const text = data.choices?.[0]?.message?.content || '';
  const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/) || [null, text];
  const results = JSON.parse(jsonMatch[1]?.trim() || text);

  const map = new Map<string, { en: string; zh: string }[]>();
  for (const r of results) {
    map.set(r.word, r.examples || []);
  }
  return map;
}

async function main() {
  console.log('Fixing final 15 words in advanced.ts...\n');

  const file = 'advanced.ts';
  const filePath = path.join(WORD_DATA_DIR, file);
  const data = extractWords(filePath);
  if (!data) { console.error('Failed to parse file'); return; }

  const missing = data.words.filter((w: any) => !w.examples || w.examples.length === 0);
  console.log(`Found ${missing.length} words without examples.`);

  // Generate examples
  const newExamples = await generateForWords(missing);

  let updated = 0;
  for (const w of data.words) {
    const ex = newExamples.get(w.word);
    if (ex && ex.length > 0) {
      w.examples = ex;
      console.log(`  ✓ ${w.word}: ${ex[0].en.slice(0, 60)}...`);
      updated++;
    }
  }

  console.log(`\nUpdated ${updated}/${missing.length} words.`);

  // Write file
  writeFile(filePath, data.varName, data.words);
  console.log(`✓ Wrote updated ${file}`);

  // Verify
  const verify = extractWords(filePath);
  if (verify) {
    const stillMissing = verify.words.filter((w: any) => !w.examples || w.examples.length === 0);
    console.log(`Verification: ${stillMissing.length} still missing`);
    if (stillMissing.length > 0) {
      for (const w of stillMissing) console.log(`  - ${w.word}`);
    }
  }
}

main().catch(e => { console.error(e); process.exit(1); });
