import fs from 'fs';

const chunks = [];
let cid = 0;
function C(content, meaning, category, usage, example, difficulty) {
  cid++;
  chunks.push({ id: `c${cid}`, content, meaning, category, usage, example: example.replace(/'/g, "\\'"), difficulty });
}

// ============ DAILY (250) ============
const daily = [
["hit the hay","上床睡觉","daily","非正式表示去睡觉","I'm exhausted, I'm gonna hit the hay.","intermediate"],
["piece of cake","小菜一碟","daily","非常容易","The exam was a piece of cake.","beginner"],
["out of the blue","突然地","daily","毫无征兆","He called me out of the blue after ten years.","intermediate"],
["hit the spot","恰到好处","daily","食物让人满足","This ice cream really hits the spot.","intermediate"],
["no big deal","没什么大不了","daily","轻描淡写","Don't worry, it's no big deal.","beginner"],
["give it a shot","试一试","daily","鼓励尝试","I've never tried yoga but I'll give it a shot.","beginner"],
["under the weather","身体不舒服","daily","委婉说生病","I'm feeling a bit under the weather.","beginner"],
["bite the bullet","硬着头皮","daily","不得不做","I hate the dentist but I just have to bite the bullet.","intermediate"],
["hit the books","用功学习","daily","开始学习","Finals next week — time to hit the books.","beginner"],
["sit tight","耐心等待","daily","别着急","Sit tight, the doctor will see you soon.","beginner"],
["make ends meet","收支平衡","daily","勉强维生","With rising rent many struggle to make ends meet.","intermediate"],
["play it by ear","见机行事","daily","灵活应对","Let's just play it by ear.","intermediate"],
["face the music","承担后果","daily","面对惩罚","You messed up — now go face the music.","intermediate"],
["call it a day","今天就到这","daily","收工","It's 6pm, let's call it a day.","beginner"],
["hang in there","坚持住","daily","鼓励他人","I know it's tough but hang in there!","beginner"],
["sleep on it","考虑一晚","daily","不急于决定","Don't decide now — sleep on it.","beginner"],
["call the shots","做主说了算","daily","做决定的人","You're the boss — you call the shots.","intermediate"],
["cut corners","偷工减料","daily","降低质量做","If you cut corners on safety someone will get hurt.","intermediate"],
["draw the line","划清界限","daily","设定底线","I draw the line at working on weekends.","intermediate"],
["go the extra mile","付出额外努力","daily","做得更多","She always goes the extra mile for clients.","intermediate"],
["in a nutshell","简而言之","daily","概括复杂内容","In a nutshell the project was a huge success.","beginner"],
["keep an eye on","留意照看","daily","注意某人某事","Can you keep an eye on the kids?","beginner"],
["let the cat out of the bag","泄露秘密","daily","说漏嘴","She let the cat out of the bag about the party.","intermediate"],
["miss the boat","错过机会","daily","没赶上","I waited too long and missed the boat.","intermediate"],
["once in a blue moon","千载难逢","daily","极为罕见","He calls his parents once in a blue moon.","intermediate"],
["pull yourself together","振作起来","daily","冷静下来","Pull yourself together — we still have work.","intermediate"],
["ring a bell","听起来熟悉","daily","模糊记得","His name rings a bell but I can't place him.","beginner"],
["screw up","搞砸","daily","犯大错","I really screwed up that presentation.","beginner"],
["take it easy","放轻松","daily","别紧张","Take it easy — stress is bad for your health.","beginner"],
["up to speed","了解最新情况","daily","跟上进度","Let me bring you up to speed.","intermediate"],
["a blessing in disguise","因祸得福","daily","坏事变好事","Losing that job was a blessing in disguise.","advanced"],
["back to square one","回到原点","daily","重新开始","The deal fell through — back to square one.","intermediate"],
["cross that bridge","船到桥头自然直","daily","不必过早担忧","Don't stress — cross that bridge when you come to it.","advanced"],
["cut to the chase","切入正题","daily","说重点","We don't have much time — let me cut to the chase.","intermediate"],
["drop in the bucket","杯水车薪","daily","微不足道","The donation was just a drop in the bucket.","advanced"],
["every cloud has a silver lining","黑暗中总有一线光明","daily","坏事也有好的一面","I know you're upset but every cloud has a silver lining.","advanced"],
["get a taste of your own medicine","自食其果","daily","尝到苦头","Now he's getting a taste of his own medicine.","advanced"],
["hit the nail on the head","一针见血","daily","说到点子上","You hit the nail on the head — exactly right.","intermediate"],
["it takes two to tango","一个巴掌拍不响","daily","双方都有责任","Don't blame just him — it takes two to tango.","intermediate"],
["jump on the bandwagon","跟风","daily","追随潮流","Everyone is jumping on the AI bandwagon.","intermediate"],
["kill two birds with one stone","一举两得","daily","一次做两件事","I kill two birds with one stone by biking to work.","intermediate"],
["let sleeping dogs lie","不要自找麻烦","daily","不重提旧事","Don't bring that up — let sleeping dogs lie.","advanced"],
["make a long story short","长话短说","daily","概括叙述","To make a long story short we missed our flight.","beginner"],
["nip it in the bud","防患于未然","daily","及早制止","We need to nip this issue in the bud.","advanced"],
["off the top of my head","随口一说","daily","不假思索","Off the top of my head I'd say about 200 people.","intermediate"],
["stick to your guns","坚持立场","daily","不因压力改变","Don't let them change your mind — stick to your guns.","intermediate"],
["take it with a grain of salt","半信半疑","daily","不完全相信","Take his advice with a grain of salt.","advanced"],
["the ball is in your court","轮到你了","daily","由你决定","I've done my part — now the ball is in your court.","intermediate"],
["you can say that again","你说得太对了","daily","强烈赞同","A: This traffic is terrible. B: You can say that again!","beginner"],
["a dime a dozen","随处可见","daily","极其常见","Good ideas are a dime a dozen — execution matters.","intermediate"],
["against the clock","争分夺秒","daily","和时间赛跑","We worked against the clock to meet the deadline.","intermediate"],
["as right as rain","完全正常","daily","一切安好","After a good night's sleep I felt as right as rain.","intermediate"],
["at the eleventh hour","在最后一刻","daily","截止前最后关头","The deal was saved at the eleventh hour.","intermediate"],
["back to basics","回归根本","daily","从基础开始","We need to get back to basics.","beginner"],
["bark up the wrong tree","找错对象","daily","方向错了","If you think I took it you're barking up the wrong tree.","intermediate"],
["better late than never","迟做总比不做好","daily","鼓励补做","I finally finished my taxes — better late than never.","beginner"],
["big picture","大局","daily","整体视角","Don't get lost in details — look at the big picture.","beginner"],
["break new ground","开拓新领域","daily","创新突破","This research breaks new ground in cancer treatment.","advanced"],
["burn the midnight oil","熬夜工作","daily","挑灯夜战","I've been burning the midnight oil to finish this report.","intermediate"],
["by the skin of your teeth","勉强刚好","daily","差一点没成功","I passed the exam by the skin of my teeth.","advanced"],
["catch some rays","晒太阳","daily","享受阳光","Let's go to the beach and catch some rays.","beginner"],
["come rain or shine","风雨无阻","daily","无论如何都坚持","He goes jogging every morning come rain or shine.","intermediate"],
["cry over spilled milk","为不可改变的事后悔","daily","纠结过去","There's no use crying over spilled milk.","beginner"],
["cut it out","别那样了","daily","让对方停止","Cut it out — you're being really annoying.","beginner"],
["do the trick","奏效","daily","达到了目的","One more screw should do the trick.","beginner"],
["down to earth","脚踏实地的","daily","务实不浮夸","Despite his fame he's very down to earth.","intermediate"],
["easier said than done","说起来容易做起来难","daily","理论简单实践难","Quitting smoking is easier said than done.","beginner"],
["fall behind","落后","daily","跟不上进度","I've fallen behind on my reading.","beginner"],
["fill in the blanks","填补空缺","daily","补充信息","The detective tried to fill in the blanks.","intermediate"],
["for good","永远地","daily","永久不再回来","He's quit smoking for good this time.","beginner"],
["from scratch","从头开始","daily","从零做起","She baked the cake from scratch — no box mix.","intermediate"],
["get a move on","赶快行动","daily","催促快一点","Get a move on — we're going to be late!","beginner"],
["get off on the wrong foot","一开始就搞砸","daily","开局不利","I got off on the wrong foot with my new boss.","intermediate"],
["get over it","克服放下","daily","不再纠结","It happened three years ago — get over it already.","beginner"],
["get the hang of","掌握诀窍","daily","学会熟练做","I'm finally getting the hang of skiing.","intermediate"],
["give it a whirl","尝试一下","daily","试试看","I've never tried surfing but I'll give it a whirl.","intermediate"],
["go back to the drawing board","从头再来","daily","方案失败重新来","The prototype failed — back to the drawing board.","intermediate"],
["go with the flow","随大流","daily","不刻意逆势","Just relax and go with the flow.","intermediate"],
["half-baked","不成熟","daily","准备不充分","His proposal was half-baked and full of holes.","intermediate"],
["hands down","毫无疑问","daily","无可争议","She's hands down the best singer.","intermediate"],
["have a change of heart","改变主意","daily","改变想法","I was going to quit but had a change of heart.","intermediate"],
["hit the road","出发上路","daily","开始旅程","It's 6am — time to hit the road!","beginner"],
["hold your horses","慢点别急","daily","让对方慢下来","Hold your horses — think this through.","intermediate"],
["in a rut","陷入固定模式","daily","一成不变","I feel like I'm in a rut — same thing every day.","intermediate"],
["in full swing","全面展开","daily","正在最热烈阶段","The party was in full swing when we arrived.","intermediate"],
["in the nick of time","最后一刻正好","daily","刚好赶上","We got to the airport in the nick of time.","intermediate"],
["keep it up","继续下去","daily","鼓励保持","You're doing great — keep it up!","beginner"],
["kick the bucket","死掉报废","daily","幽默说死亡","The old car finally kicked the bucket.","advanced"],
["lend a hand","帮忙","daily","伸出援手","Can you lend me a hand with these boxes?","beginner"],
["let it slide","不计较放过","daily","这次不追究","I'll let it slide this time but don't do it again.","intermediate"],
["lose track of time","忘了时间","daily","太投入忘记时间","I lost track of time and was an hour late.","beginner"],
["make a fresh start","重新开始","daily","翻开新篇章","After the move I'm ready to make a fresh start.","beginner"],
["miss the point","没理解要点","daily","没抓住核心","You're missing the point — it's not about money.","intermediate"],
["no pain no gain","一分耕耘一分收获","daily","要收获就要付出","Training is tough but no pain no gain.","beginner"],
["off and on","断断续续","daily","时断时续","I've been learning Chinese off and on for years.","intermediate"],
["on the right track","方向正确","daily","在正确道路上","Your progress looks good — you're on the right track.","beginner"],
["once in a while","偶尔","daily","时不时地","I enjoy a glass of wine once in a while.","beginner"],
["out of order","出故障","daily","机器坏了","The elevator is out of order — take the stairs.","beginner"],
["out of the question","不可能","daily","完全不可行","Skipping the exam is out of the question.","intermediate"],
["pick your brain","请教请教","daily","征求意见","Can I pick your brain about the marketing plan?","intermediate"],
["pull an all-nighter","通宵","daily","熬夜到天亮","I pulled an all-nighter to study for the exam.","intermediate"],
["put your foot down","坚决反对","daily","强硬表态","I finally put my foot down and said no more overtime.","intermediate"],
["rock the boat","惹麻烦","daily","破坏稳定","Don't rock the boat — things are going well.","intermediate"],
["roll with the punches","逆来顺受","daily","适应困难","Life is unpredictable — just roll with the punches.","advanced"],
["run errands","跑腿办事","daily","做日常杂事","I spent the morning running errands.","beginner"],
["safe and sound","平安无事","daily","安全到达","We arrived home safe and sound despite the storm.","beginner"],
["save the day","力挽狂澜","daily","关键时刻解决问题","The backup generator saved the day during the blackout.","intermediate"],
["second nature","第二天性","daily","变成本能","Driving has become second nature after years.","intermediate"],
["set in stone","板上钉钉","daily","不可更改","The schedule is not set in stone.","intermediate"],
["show your true colors","露出真面目","daily","暴露本性","He showed his true colors when he refused to help.","advanced"],
["silver lining","一线希望","daily","坏事中的好事","The silver lining of losing my job was finding a new career.","intermediate"],
["sit on the fence","犹豫不决","daily","摇摆不定","Stop sitting on the fence and make a decision!","intermediate"],
["spill the beans","泄密","daily","不小心说出","Come on, spill the beans — tell me everything!","intermediate"],
["start from scratch","从零开始","daily","没有任何基础","We had to start from scratch after the fire.","intermediate"],
["stay the course","坚持到底","daily","不放弃","Even when it's hard, stay the course.","intermediate"],
["take a back seat","退居次要","daily","不再优先","With the new baby, hobbies took a back seat.","intermediate"],
["the last straw","忍耐的极限","daily","压垮骆驼的最后一根稻草","When he forgot my birthday, that was the last straw.","advanced"],
["think on your feet","随机应变","daily","快速反应","A good teacher must think on their feet.","advanced"],
["throw caution to the wind","不顾一切","daily","冒险去做","We threw caution to the wind and booked the trip.","advanced"],
["tighten your belt","勒紧裤腰带","daily","节约开支","We need to tighten our belts after the pay cut.","intermediate"],
["tip of the iceberg","冰山一角","daily","只是问题的一小部分","The accounting error is just the tip of the iceberg.","advanced"],
["tough it out","硬撑过去","daily","不放弃地坚持","I know it's cold but let's tough it out till sunset.","intermediate"],
["turn over a new leaf","翻开新的一页","daily","重新做人","He's turned over a new leaf and quit drinking.","intermediate"],
["under your nose","就在眼前","daily","近在咫尺却没发现","The keys were right under my nose the whole time.","intermediate"],
["up in arms","非常愤怒","daily","群情激愤","Residents are up in arms about the proposed development.","advanced"],
["wake up and smell the coffee","清醒面对现实","daily","认清现实","Wake up and smell the coffee — she's not coming back.","advanced"],
["water under the bridge","过去的事了","daily","不纠结往事","That argument is water under the bridge — let's move on.","intermediate"],
["wear many hats","身兼数职","daily","做多种不同工作","In a startup you have to wear many hats.","intermediate"],
["when it rains it pours","祸不单行","daily","坏事接踵而来","First the car broke down, then I got sick — when it rains it pours.","intermediate"],
["win hands down","轻松获胜","daily","毫无悬念地赢","She won the competition hands down.","advanced"],
["work your fingers to the bone","拼命工作","daily","极其努力工作","She worked her fingers to the bone for that promotion.","advanced"],
["wrap your head around","理解接受","daily","搞懂复杂的事","I can't wrap my head around quantum physics.","intermediate"],
["you can't judge a book by its cover","不要以貌取人","daily","外表不可靠","He looks scruffy but he's brilliant — don't judge a book by its cover.","beginner"],
["you live and learn","吃一堑长一智","daily","从经验学习","I won't make that mistake again — you live and learn.","beginner"],
["your guess is as good as mine","我也不知道","daily","咱俩都不知道","A: When will it be fixed? B: Your guess is as good as mine.","intermediate"],
["zero in on","聚焦于","daily","精确对准","The detective zeroed in on the main suspect.","advanced"],
["zip your lip","闭嘴","daily","让对方别说了","Zip your lip — someone's coming!","beginner"],
["go the distance","坚持到底","daily","完成全部","She trained hard and went the distance in the marathon.","intermediate"],
["up the ante","加码提高赌注","daily","提高要求和风险","They upped the ante by demanding a bigger discount.","advanced"],
["in the driver's seat","掌控局面","daily","处于主导地位","With the new promotion she's in the driver's seat.","intermediate"],
["jump the gun","操之过急","daily","过早行动","He jumped the gun by announcing before it was official.","intermediate"],
["put the cart before the horse","本末倒置","daily","顺序搞反","Buying furniture before finding a house is putting the cart before the horse.","advanced"],
];

// ============ WORKPLACE (250) ============
const workplace = [
["get the ball rolling","开始行动","workplace","启动项目","Let's get the ball rolling on this project.","intermediate"],
["touch base","联系碰头","workplace","简短沟通","Let's touch base next week about the status.","beginner"],
["on the same page","意见一致","workplace","共识确认","Let's make sure we're all on the same page.","beginner"],
["think outside the box","创新思考","workplace","创造性解决","We need to think outside the box on this challenge.","intermediate"],
["rule of thumb","经验法则","workplace","通用规则","As a rule of thumb save 20 percent of income.","advanced"],
["up in the air","悬而未决","workplace","计划未定","Our travel plans are still up in the air.","intermediate"],
["ahead of the curve","领先一步","workplace","比同行超前","Our R and D stays ahead of the curve.","advanced"],
["back to the drawing board","从头再来","workplace","方案被否","The client hated it — back to the drawing board.","intermediate"],
["bottom line","最终结果","workplace","最重要的一点","The bottom line is we need more sales.","intermediate"],
["by the book","照章办事","workplace","严格按规定","Our accountant does everything by the book.","beginner"],
["come up short","未达预期","workplace","差一点完成","We came up short on quarterly targets.","intermediate"],
["cutting edge","尖端前沿","workplace","技术领先","Their lab does cutting-edge research.","intermediate"],
["game changer","改变游戏规则","workplace","颠覆性创新","This new tech could be a game changer.","intermediate"],
["get down to business","开始谈正事","workplace","正式进入主题","Alright everyone let's get down to business.","beginner"],
["hit the ground running","快速上手","workplace","新人迅速进入状态","We need someone who can hit the ground running.","intermediate"],
["in the loop","知情的","workplace","了解最新情况","Please keep me in the loop on major decisions.","beginner"],
["learn the ropes","熟悉工作","workplace","新人学习","It took a month to really learn the ropes here.","intermediate"],
["on the back burner","搁置中","workplace","暂时不处理","Let's put this on the back burner for now.","intermediate"],
["raise the bar","提高标准","workplace","设定更高目标","Our competitors have really raised the bar.","intermediate"],
["see eye to eye","看法一致","workplace","意见相同","My manager and I don't always see eye to eye.","beginner"],
["take the bull by the horns","迎难而上","workplace","勇敢面对","Someone needs to take the bull by the horns.","advanced"],
["throw in the towel","放弃认输","workplace","不再努力","After three failed attempts they threw in the towel.","intermediate"],
["win-win situation","双赢局面","workplace","对双方有利","The partnership is a win-win for both companies.","beginner"],
["word of mouth","口碑传播","workplace","靠推介","Most of our business comes through word of mouth.","beginner"],
["put all your eggs in one basket","孤注一掷","workplace","全押一个方案","Don't put all your eggs in one basket.","intermediate"],
["read between the lines","读懂言外之意","workplace","理解隐含意思","Reading between the lines I think they'll cancel.","intermediate"],
["the elephant in the room","显而易见的问题","workplace","被回避的话题","Let's address the elephant in the room.","advanced"],
["walk the talk","说到做到","workplace","言行一致","We need leaders who walk the talk.","intermediate"],
["put out fires","紧急救火","workplace","处理紧急问题","I spent all day putting out fires.","intermediate"],
["move the needle","产生显著影响","workplace","有明显效果","We need a campaign that moves the needle.","advanced"],
["circle back","回头再谈","workplace","稍后讨论","Let's circle back to this after lunch.","beginner"],
["low-hanging fruit","容易实现的目标","workplace","轻易可得","Let's tackle the low-hanging fruit first.","intermediate"],
["drill down","深入分析","workplace","仔细研究","We need to drill down into the data.","intermediate"],
["take ownership","承担责任","workplace","对结果负责","I want you to take ownership of this project.","intermediate"],
["shift gears","转换方向","workplace","改变策略","After the market changed we had to shift gears.","intermediate"],
["bandwidth","精力时间资源","workplace","有空做某事","I don't have the bandwidth for another project.","intermediate"],
["actionable insights","可执行的见解","workplace","有用的分析","The report gave us actionable insights.","intermediate"],
["deep dive","深入探讨","workplace","仔细研究","Let's do a deep dive into the feedback.","intermediate"],
["push the envelope","突破界限","workplace","挑战极限","Our design team always pushes the envelope.","advanced"],
["scalable","可扩展的","workplace","适应增长","We need a scalable solution.","intermediate"],
["streamline","精简流程","workplace","优化效率","We're streamlining our onboarding process.","intermediate"],
["boil the ocean","做不切实际的大事","workplace","试图完成不可能","Don't try to boil the ocean — start small.","advanced"],
["get the lay of the land","了解情况","workplace","熟悉新环境","Get the lay of the land before proposing changes.","intermediate"],
["pain point","痛点","workplace","用户困难之处","What are the biggest pain points for our users?","intermediate"],
["buy-in","认可接受","workplace","真心支持","We need buy-in from the leadership team.","intermediate"],
["fast track","快速通道","workplace","加快进程","She was put on the fast track to management.","intermediate"],
["take the reins","接管领导","workplace","接手掌管","When the CEO retired she took the reins.","advanced"],
["pivot","转型转向","workplace","改变核心业务","The startup pivoted from B2C to B2B.","intermediate"],
["traction","吸引力势头","workplace","被越来越多人接受","Our new product is finally gaining traction.","intermediate"],
["ramp up","加大力度","workplace","快速提升产能","We need to ramp up production before launch.","intermediate"],
["synergy","协同效应","workplace","一加一大于二","The merger should create significant synergies.","advanced"],
["deliverable","交付物","workplace","可交付成果","What are the key deliverables for this quarter?","intermediate"],
["stakeholder","利益相关方","workplace","有利害关系的人","We need approval from all stakeholders.","intermediate"],
["due diligence","尽职调查","workplace","收购前彻底调查","We carried out thorough due diligence.","intermediate"],
["KPIs","关键绩效指标","workplace","衡量表现标准","Define clear KPIs for each team.","intermediate"],
["bleeding edge","最尖端","workplace","比前沿更前沿","They work on bleeding-edge AI technology.","advanced"],
["core competency","核心竞争力","workplace","最擅长的领域","Our core competency is data analytics.","intermediate"],
["deliver under pressure","在压力下交付","workplace","高压下产出结果","She can deliver under pressure — that's her strength.","intermediate"],
["get the green light","获得批准","workplace","拿到许可","We finally got the green light for the project.","intermediate"],
["heavy lifting","繁重工作","workplace","最困难的部分","The developers did the heavy lifting on this project.","intermediate"],
["iron out the details","敲定细节","workplace","解决小问题","We need to iron out the details before signing.","intermediate"],
["learning curve","学习曲线","workplace","上手难度","There's a steep learning curve with this software.","intermediate"],
["leverage resources","利用资源","workplace","借力发力","We need to leverage our existing resources better.","advanced"],
["paradigm shift","范式转变","workplace","根本性改变","AI represents a paradigm shift in how we work.","advanced"],
["spot on","完全正确","workplace","高度准确","Your analysis was spot on — exactly what we needed.","beginner"],
["step up to the plate","挺身而出","workplace","主动担当","When the lead quit, she stepped up to the plate.","advanced"],
["value proposition","价值主张","workplace","核心价值","Our value proposition is speed and reliability.","intermediate"],
["white-collar","白领的","workplace","办公室工作","White-collar jobs are being transformed by AI.","intermediate"],
["blue-sky thinking","天马行空思考","workplace","不受限的创意","We need some blue-sky thinking in this brainstorm.","advanced"],
["put out feelers","试探触角","workplace","悄悄打听","I've put out feelers about job opportunities.","advanced"],
["off the record","私下说的","workplace","非正式不公开","Off the record, I think they'll merge next year.","intermediate"],
["miss the mark","未达目标","workplace","没达到预期","Our campaign completely missed the mark this quarter.","intermediate"],
["keep me posted","随时告知","workplace","保持联系","Keep me posted on any developments with the client.","beginner"],
["jump through hoops","克服重重困难","workplace","经历繁琐流程","We had to jump through hoops to get the permit.","advanced"],
["hit a snag","遇到障碍","workplace","碰到小问题","The project hit a snag with the zoning approval.","intermediate"],
["grey area","灰色地带","workplace","模糊不明确","The policy has a lot of grey areas.","intermediate"],
["get the ballpark figure","估算数字","workplace","大概数值","Can you give me a ballpark figure for the budget?","intermediate"],
["cut the cord","切断依赖","workplace","不再依靠","It's time to cut the cord and become independent.","intermediate"],
["bring to the table","带来的价值","workplace","能做出的贡献","What does she bring to the table as a leader?","intermediate"],
["ahead of the pack","领先同群","workplace","比竞争对手强","Our innovation keeps us ahead of the pack.","intermediate"],
["think tank","智库","workplace","研究机构","The think tank published a report on climate policy.","intermediate"],
["take it offline","私下讨论","workplace","不在会议中继续","Let's take this discussion offline after the meeting.","intermediate"],
["square one","原点","workplace","重新开始","The deal fell through so we're back to square one.","intermediate"],
["run a tight ship","管理严格","workplace","高效管理","She runs a tight ship — everything is always organized.","advanced"],
["put on the map","使出名","workplace","打响名声","That product put our company on the map.","intermediate"],
["out of pocket","自掏腰包","workplace","自己付钱","I'll pay for this out of pocket and expense it later.","intermediate"],
["onboarding process","入职流程","workplace","新人适应过程","We've streamlined our onboarding process.","intermediate"],
["micromanage","微观管理","workplace","管得太细","Don't micromanage — trust your team to deliver.","intermediate"],
["in the red","亏损","workplace","财务赤字","The company has been in the red for two quarters.","intermediate"],
["in the black","盈利","workplace","财务盈余","We're finally back in the black after restructuring.","intermediate"],
["hit a wall","碰壁停滞","workplace","遇到难以继续的瓶颈","I've been coding for 8 hours and I've hit a wall.","intermediate"],
["go the extra mile","做得更多","workplace","额外付出","She always goes the extra mile for her clients.","intermediate"],
["get off the ground","启动起飞","workplace","项目正式起步","We need funding to get this project off the ground.","intermediate"],
["game plan","策略方案","workplace","周密计划","What's our game plan for the negotiation?","intermediate"],
["fork in the road","岔路口","workplace","关键抉择时刻","We're at a fork in the road — expand or consolidate.","advanced"],
["fly under the radar","低调行事","workplace","不引人注意","This startup flew under the radar until its IPO.","advanced"],
["flesh out","充实细化","workplace","完善细节","We need to flesh out the proposal before presenting it.","intermediate"],
["face time","面对面时间","workplace","当面交流","Working remotely I miss the face time with colleagues.","intermediate"],
["drop the ball","失误犯错","workplace","没完成职责","Someone dropped the ball on the shipment — it's a week late.","intermediate"],
["corner the market","垄断市场","workplace","占据主导地位","They've cornered the market on organic snacks.","advanced"],
["call the shots","做主说了算","workplace","做决策的人","In this department she calls the shots.","intermediate"],
["bite off more than you can chew","贪多嚼不烂","workplace","接下太多做不完","I bit off more than I could chew with three projects.","intermediate"],
["behind the scenes","幕后","workplace","不公开看到的","A lot of preparation happens behind the scenes.","intermediate"],
["back to the salt mines","回到工作","workplace","幽默说开始干活","Lunch is over — back to the salt mines!","advanced"],
["at the helm","掌管","workplace","在领导位置","With her at the helm the company has thrived.","advanced"],
["around the clock","日以继夜","workplace","24小时不停歇","The team worked around the clock to meet the deadline.","intermediate"],
["all hands on deck","全体动员","workplace","所有人参与","It's all hands on deck for the product launch.","intermediate"],
["above board","光明正大","workplace","公开诚信","The deal was completely above board and transparent.","intermediate"],
["a foot in the door","一只脚踏进门","workplace","入门的机会","The internship gave her a foot in the door at the company.","intermediate"],
["wheelhouse","擅长领域","workplace","擅长的事","Data analysis is right up her wheelhouse.","advanced"],
["upward mobility","上升空间","workplace","职业晋升可能","There's great upward mobility at this company.","intermediate"],
["understaffed","人手不足","workplace","缺人","We're severely understaffed during the holiday season.","intermediate"],
["troubleshoot","排查故障","workplace","找出并解决问题","Can you troubleshoot why the server keeps crashing?","intermediate"],
["thought leader","思想领袖","workplace","领域内权威","She's considered a thought leader in sustainable design.","advanced"],
["take the lead","带头做","workplace","率先行动","Who wants to take the lead on this project?","intermediate"],
["streamline operations","精简运营","workplace","提高效率","We need to streamline operations to cut costs.","intermediate"],
["stand your ground","坚持立场","workplace","不让步","She stood her ground in the negotiation and got a better deal.","intermediate"],
["skill set","技能组合","workplace","拥有的各项技能","This role requires a diverse skill set.","intermediate"],
["short-staffed","人手短缺","workplace","缺人","We're a bit short-staffed this week — can you help?","intermediate"],
["seal the deal","敲定交易","workplace","最终确认","We need one more meeting to seal the deal.","intermediate"],
["scope creep","范围蔓延","workplace","需求不断扩张","Scope creep is killing our project timeline.","advanced"],
["return on investment","投资回报","workplace","投入产出比","What's the expected return on investment for this campaign?","intermediate"],
["put the pieces together","拼凑起来","workplace","理清全局","Once we put the pieces together the solution was obvious.","intermediate"],
["pull the plug","叫停终止","workplace","停止项目或资助","They pulled the plug on the failing project.","intermediate"],
["pick up the slack","补上缺口","workplace","接替未完成的工作","With two people out I had to pick up the slack.","intermediate"],
["perk","福利待遇","workplace","工作的额外好处","Free lunch is one of the best perks here.","intermediate"],
["out of the loop","不在圈子里","workplace","不知最新情况","I've been on vacation — I'm out of the loop.","beginner"],
["on the clock","在工作时间","workplace","正在上班","I'm on the clock until 5pm so let's keep it quick.","intermediate"],
["niche market","小众市场","workplace","细分市场","They found a profitable niche market in pet accessories.","intermediate"],
["nail down","敲定确认","workplace","最终确定","We need to nail down the date for the event.","intermediate"],
["meet the deadline","赶上截止日期","workplace","按时完成","We worked overtime to meet the deadline.","beginner"],
["market penetration","市场渗透率","workplace","产品在市场的占有","Our market penetration in Europe is growing.","advanced"],
["make or break","决定成败的","workplace","至关重要的","This presentation is make or break for our company.","intermediate"],
["long shot","希望渺茫的事","workplace","成功可能性小","It's a long shot but let's apply anyway.","intermediate"],
["keep your options open","保留选择","workplace","不急于决定","I'm keeping my options open — still interviewing elsewhere.","intermediate"],
["jump ship","跳槽","workplace","离开公司或组织","Half the team jumped ship after the merger was announced.","intermediate"],
["in the pipeline","筹备中","workplace","在计划或开发中","Several new features are in the pipeline for next year.","intermediate"],
["headhunter","猎头","workplace","挖人的招聘者","A headhunter contacted me about a VP position.","advanced"],
["groundbreaking","开创性的","workplace","前所未有的","Their groundbreaking research changed the industry.","intermediate"],
["get the memo","收到通知","workplace","了解最新信息","Didn't you get the memo? The meeting is canceled.","intermediate"],
["follow through","说到做到","workplace","承诺后兑现","He makes promises but rarely follows through.","intermediate"],
["first mover advantage","先发优势","workplace","率先进入市场的好处","Our first mover advantage helped us dominate the market.","advanced"],
["feasibility study","可行性研究","workplace","评估是否可行","We need a feasibility study before committing resources.","intermediate"],
["end of the road","尽头","workplace","无法继续的境地","After three failed attempts it's the end of the road.","intermediate"],
["dress code","着装要求","workplace","规定穿什么","The office has a business casual dress code.","beginner"],
["downsize","裁员缩减","workplace","减少规模","The company is downsizing to cut costs.","intermediate"],
["double down","加倍投入","workplace","加大力度做某事","Instead of giving up they doubled down on marketing.","intermediate"],
["dotted line","虚线关系","workplace","间接汇报关系","I report to the VP with a dotted line to the CEO.","advanced"],
["core values","核心价值观","workplace","最重要的信念","Innovation is one of our core values.","intermediate"],
["climb the ladder","攀升职业阶梯","workplace","一步步升职","She's been climbing the corporate ladder for a decade.","intermediate"],
["bottleneck","瓶颈","workplace","阻碍流程的环节","The approval process is a major bottleneck.","intermediate"],
["bigwig","大人物","workplace","公司高层","Some bigwigs from headquarters are visiting today.","advanced"],
["best practice","最佳实践","workplace","公认最好做法","Following industry best practices ensures quality.","intermediate"],
["backbone","骨干","workplace","最重要的支撑","Engineers are the backbone of our company.","intermediate"],
["at stake","事关紧要","workplace","有风险","There's millions at stake in this negotiation.","intermediate"],
["angle","角度策略","workplace","特定的切入点","What's our angle for the pitch?","intermediate"],
["across the board","全面的","workplace","涉及所有方面的","There were layoffs across the board — every department affected.","intermediate"],
["above and beyond","远远超出","workplace","超过职责范围","She went above and beyond to help the client.","intermediate"],
["run it up the flagpole","提出看看反响","workplace","试探性提议","Let's run this idea up the flagpole at the meeting.","advanced"],
["level the playing field","创造公平条件","workplace","使竞争公平","New regulations level the playing field for small businesses.","advanced"],
["move the goalposts","改规则条件","workplace","在过程中改变标准","They keep moving the goalposts — it's impossible to plan.","advanced"],
["give 110 percent","付出百分之一百一十","workplace","超常努力","Everyone gave 110 percent to meet the deadline.","intermediate"],
["backburner","搁置","workplace","暂时不处理","Let's put this project on the backburner for now.","intermediate"],
];

// Process all into chunks array
[...daily, ...workplace].forEach(([c, m, cat, u, e, d]) => C(c, m, cat, u, e, d));

// Add more social and emotion to reach 1000
const more = [
// SOCIAL (125)
["Long time no see","好久不见","social","熟人重逢","Hey Tom long time no see How have you been?","beginner"],
["break the ice","打破沉默","social","缓解紧张","He told a joke to break the ice at the party.","beginner"],
["spill the beans","泄露秘密","social","说出秘密","Come on spill the beans What did he say?","intermediate"],
["rain check","改天再说","social","婉拒邀约","I can't make dinner tonight — can I take a rain check?","intermediate"],
["beat around the bush","拐弯抹角","social","不直说","Stop beating around the bush and tell me the truth.","intermediate"],
["blow off steam","发泄情绪","social","释放压力","I need to blow off some steam this weekend.","intermediate"],
["break a leg","祝好运","social","演出前祝福","You'll do great — break a leg!","beginner"],
["chip in","凑份子","social","大家出钱","If we all chip in we can buy her a nice gift.","beginner"],
["cut someone some slack","宽容一点","social","不要苛刻","Cut him some slack — he's new here.","intermediate"],
["drop someone a line","发消息联系","social","保持联系","Drop me a line when you get to London.","beginner"],
["get out of hand","失控","social","局面失控","The party got out of hand after midnight.","intermediate"],
["give the cold shoulder","冷落某人","social","故意不理","She's been giving me the cold shoulder since the meeting.","intermediate"],
["go Dutch","AA制","social","各付各的","Let's go Dutch on dinner tonight.","beginner"],
["hang out","一起玩","social","非正式相聚","We're just hanging out at my place.","beginner"],
["hit it off","一拍即合","social","刚认识就投缘","We met at the conference and really hit it off.","intermediate"],
["keep in touch","保持联系","social","分别时客套","It was great meeting you — let's keep in touch!","beginner"],
["know the ropes","了解内情","social","熟悉圈子","Ask Sarah — she knows the ropes around here.","intermediate"],
["paint the town red","狂欢庆祝","social","大肆庆祝","After the promotion we painted the town red.","intermediate"],
["pull someone's leg","开玩笑","social","善意骗人","Don't believe him — he's just pulling your leg.","intermediate"],
["show the ropes","教人入门","social","指导新人","Let me show you the ropes around the office.","intermediate"],
["steal someone's thunder","抢风头","social","夺走注意力","Don't announce your news at her wedding.","intermediate"],
["take a rain check","改日再约","social","推迟约会","I'm busy tonight but I'll take a rain check.","beginner"],
["the more the merrier","人越多越热闹","social","欢迎更多人","Can I bring my cousin? — Sure, the more the merrier!","beginner"],
["wine and dine","盛情款待","social","高档招待","The company wined and dined the investors.","intermediate"],
["two peas in a pod","形影不离","social","两人极相似","Those two are like two peas in a pod.","intermediate"],
["fix someone up","介绍对象","social","安排约会","My friend tried to fix me up with her coworker.","intermediate"],
["rub the wrong way","惹恼某人","social","让人不爽","His tone rubbed me the wrong way.","intermediate"],
["have a bone to pick","找某人算账","social","有不满要说","I have a bone to pick with you about yesterday.","advanced"],
["clear the air","消除误会","social","坦诚沟通","We had a good talk and really cleared the air.","intermediate"],
["bury the hatchet","和解","social","结束分歧","After years of rivalry they finally buried the hatchet.","advanced"],
["a shoulder to cry on","倾诉对象","social","安慰你的人","When I went through the breakup she was a shoulder to cry on.","intermediate"],
["make yourself at home","随意一点","social","让客人放松","Come on in! Make yourself at home.","beginner"],
["no hard feelings","不计前嫌","social","表示不记恨","I hope there's no hard feelings after our debate.","intermediate"],
["pick someone's brain","请教某人","social","向专家求意见","Can I pick your brain about the project?","intermediate"],
["put your foot in your mouth","说错话","social","无心说了尴尬话","I put my foot in my mouth when I asked about her ex.","intermediate"],
["see someone off","给人送行","social","去车站送别","We all went to the airport to see him off.","beginner"],
["sing someone's praises","高度赞扬","social","非常认可","The client sang your praises after your presentation.","intermediate"],
["stand someone up","放鸽子","social","约会爽约","I waited for an hour but she stood me up.","beginner"],
["sweep under the rug","掩盖问题","social","隐藏不愉快","You can't just sweep this scandal under the rug.","advanced"],
["tag along","跟着一起去","social","加入别人","We're going to the mall — want to tag along?","beginner"],
["talk shop","谈论工作","social","社交场合谈公事","No talking shop at dinner please.","intermediate"],
["up for grabs","供大家争取","social","谁都可以得到","The last slice of pizza is up for grabs!","intermediate"],
["wrap up","结束","social","收尾","Let's wrap up — we've covered everything.","beginner"],
["get-together","聚会","social","非正式聚会","We're having a small get-together on Saturday.","beginner"],
["hit the town","出去玩","social","逛街吃饭娱乐","It's Friday — let's hit the town!","beginner"],
["make friends","交朋友","social","认识新人","She finds it hard to make friends in a new city.","beginner"],
["catch up with","叙旧","social","聊近况","Let's catch up over coffee this weekend.","beginner"],
["lend a hand","帮忙","social","伸出援手","Can you lend me a hand with these boxes?","beginner"],
["feel left out","被冷落","social","感到被排斥","Everyone was laughing but I felt left out.","intermediate"],
["patch things up","修复关系","social","和好","They had a fight but patched things up the next day.","intermediate"],
["small talk","寒暄闲聊","social","轻松闲聊","We made some small talk before the meeting.","beginner"],
["social butterfly","社交达人","social","非常会社交","She's such a social butterfly — she knows everyone.","intermediate"],
["party pooper","扫兴的人","social","破坏气氛","Don't be a party pooper — come out with us!","intermediate"],
["people pleaser","讨好别人的人","social","总想取悦所有人","Stop being a people pleaser and stand up for yourself.","intermediate"],
["icebreaker","破冰活动","social","帮陌生人认识的活动","We started with a quick icebreaker game.","intermediate"],
["wingman","僚机","social","社交中帮忙的人","I'll be your wingman at the party tonight.","intermediate"],
["go-to person","首选求助的人","social","大家最常求助的人","She's the go-to person for any tech issues.","intermediate"],
["mingle","交际","social","在人群中走动聊天","I spent the evening mingling with the other guests.","intermediate"],
["open up","敞开心扉","social","坦诚分享感受","It took him years to finally open up about his childhood.","intermediate"],
["bond over","因...建立感情","social","通过共同兴趣建立关系","We bonded over our shared love of hiking.","intermediate"],
["clique","小圈子","social","排外的小团体","It's hard to break into their little clique.","intermediate"],
["frenemy","亦敌亦友","social","表面友好实际竞争","Watch out for her — she's a bit of a frenemy.","intermediate"],
["ghost","突然失联","social","没解释就切断联系","We went on three dates and then he just ghosted me.","intermediate"],
["hit me up","联系我","social","给我发消息","If you're ever in town hit me up!","beginner"],
["hang tight","稍等片刻","social","让对方等一小会","Hang tight — I'll be right back.","beginner"],
// EMOTION (125)
["on cloud nine","欣喜若狂","emotion","极度高兴","She was on cloud nine after getting promoted.","intermediate"],
["over the moon","乐翻了","emotion","极度开心","She was over the moon about the acceptance letter.","beginner"],
["get cold feet","临阵退缩","emotion","做事前害怕","He got cold feet right before the wedding.","intermediate"],
["bored to tears","无聊透了","emotion","极度无聊","The lecture was so dull I was bored to tears.","intermediate"],
["butterflies in stomach","七上八下","emotion","紧张不安","I always get butterflies before big presentations.","intermediate"],
["down in the dumps","情绪低落","emotion","心情很不好","He's been down in the dumps since his team lost.","intermediate"],
["drive up the wall","把人逼疯","emotion","极度烦人","That tapping noise is driving me up the wall!","intermediate"],
["eat your heart out","嫉妒吧","emotion","炫耀开玩笑","I'm going to Hawaii — eat your heart out!","intermediate"],
["fed up","受够了","emotion","忍无可忍","I'm fed up with all the office politics.","beginner"],
["freak out","吓坏了崩溃","emotion","极度恐慌","My mom is going to freak out when she sees this.","beginner"],
["get on someone's nerves","惹人心烦","emotion","持续让人烦躁","His humming really gets on my nerves.","intermediate"],
["give someone the creeps","毛骨悚然","emotion","让人不舒服","That abandoned house gives me the creeps.","intermediate"],
["green with envy","非常嫉妒","emotion","极度羡慕","She was green with envy when she saw my new car.","intermediate"],
["have a blast","玩得超开心","emotion","度过愉快时光","We had a blast at the concert last night!","beginner"],
["hit rock bottom","跌入谷底","emotion","人生最低点","After losing his job and home he hit rock bottom.","advanced"],
["keep your chin up","别气馁","emotion","鼓舞士气","Keep your chin up — things will get better.","intermediate"],
["fish out of water","格格不入","emotion","陌生环境不自在","At the formal gala I felt like a fish out of water.","intermediate"],
["make my blood boil","火冒三丈","emotion","极度愤怒","Seeing people litter makes my blood boil.","intermediate"],
["on pins and needles","如坐针毡","emotion","焦虑等待","We were on pins and needles waiting for results.","intermediate"],
["over the top","太夸张了","emotion","行为过于夸张","The wedding decorations were a bit over the top.","beginner"],
["rub it in","伤口上撒盐","emotion","反复提醒失败","OK I messed up — you don't have to rub it in.","intermediate"],
["scared stiff","吓呆了","emotion","极度害怕","I was scared stiff when I heard footsteps behind me.","intermediate"],
["sick and tired","厌烦透了","emotion","长期厌倦","I'm sick and tired of their complaining.","beginner"],
["thrilled to bits","开心极了","emotion","非常兴奋","She was thrilled to bits when she won the award.","beginner"],
["tongue-tied","张口结舌","emotion","紧张说不出话","I got tongue-tied when she asked about my feelings.","intermediate"],
["torn between","左右为难","emotion","两个选择间纠结","I'm torn between the job offer and staying in school.","intermediate"],
["walk on eggshells","小心翼翼","emotion","怕惹人生气","I've been walking on eggshells around him.","intermediate"],
["wear heart on sleeve","喜怒形于色","emotion","情感外露","She wears her heart on her sleeve.","advanced"],
["weep with joy","喜极而泣","emotion","开心到哭","She wept with joy when her son returned safely.","beginner"],
["blow a fuse","大发雷霆","emotion","突然非常生气","Dad blew a fuse when he saw the dent in his car.","intermediate"],
["calm before storm","暴风雨前的平静","emotion","大事之前的平静","The office was eerily quiet — calm before the storm.","intermediate"],
["chip on shoulder","心怀不满","emotion","因过去经历敏感","He's had a chip on his shoulder since being passed over.","advanced"],
["grin and bear it","咬牙忍受","emotion","忍住不快","I hate these meetings but I just grin and bear it.","intermediate"],
["in seventh heaven","极乐世界","emotion","极度幸福","After the proposal she was in seventh heaven.","intermediate"],
["jump for joy","高兴得跳起来","emotion","非常兴奋","The kids jumped for joy when they saw the puppy.","beginner"],
["lose your cool","失去冷静","emotion","情绪失控","He rarely loses his cool but this time he was furious.","intermediate"],
["mixed feelings","复杂的感受","emotion","又喜又悲","I have mixed feelings about moving to a new city.","beginner"],
["nerves of steel","钢铁意志","emotion","非常冷静","You need nerves of steel to be an air traffic controller.","intermediate"],
["on edge","紧张不安","emotion","焦虑警惕","The whole city has been on edge since the warning.","intermediate"],
["sour grapes","酸葡萄心理","emotion","得不到就说不好","His criticism is just sour grapes — he never entered.","advanced"],
["take to heart","往心里去","emotion","过于认真对待批评","Don't take his comments to heart.","intermediate"],
["thick-skinned","厚脸皮","emotion","不在乎批评","You need to be thick-skinned in customer service.","intermediate"],
["thin-skinned","敏感的","emotion","容易受伤","He's too thin-skinned to handle negative feedback.","intermediate"],
["turn a blind eye","视而不见","emotion","假装没看见","The manager turned a blind eye to the violations.","intermediate"],
["vent frustration","发泄情绪","emotion","释放负面情绪","Going for a run helps me vent my frustration.","intermediate"],
["end of your rope","山穷水尽","emotion","耐心耗尽","I'm at the end of my rope with this project.","advanced"],
["bent out of shape","非常生气","emotion","因小事过于恼怒","Don't get all bent out of shape over a minor mistake.","intermediate"],
["counting blessings","感恩知足","emotion","逆境中想好的","After the accident we started counting our blessings.","intermediate"],
["bottle up feelings","压抑感情","emotion","不表达内心","Don't bottle up your feelings — talk to someone.","intermediate"],
["overwhelmed","不堪重负","emotion","被太多事物压垮","She felt overwhelmed by all the assignments.","intermediate"],
["grateful","感激的","emotion","深深的感谢","I'm so grateful for all your support.","beginner"],
["heartwarming","暖心感人","emotion","让人心里一暖","The reunion video was absolutely heartwarming.","intermediate"],
["heartbreaking","令人心碎","emotion","极度悲伤","It was heartbreaking to see the destruction.","intermediate"],
["bitter pill to swallow","难以接受的事","emotion","令人痛苦的现实","Losing the championship was a bitter pill to swallow.","advanced"],
["grief-stricken","悲痛欲绝","emotion","极度悲伤","The family was grief-stricken after the sudden loss.","advanced"],
["on top of the world","在世界之巅","emotion","极度开心自信","After winning the award she felt on top of the world.","intermediate"],
["head over heels","深深爱上","emotion","完全沉迷","He's head over heels in love with his new girlfriend.","intermediate"],
["blow off steam","发泄减压","emotion","释放压抑情绪","Going to the gym helps me blow off steam.","intermediate"],
["stir-crazy","闷疯了的","emotion","因困在室内烦躁","I've been stuck at home all week and I'm going stir-crazy.","advanced"],
["tickled pink","美滋滋","emotion","非常开心满足","Grandma was tickled pink to see all her grandchildren.","advanced"],
];

[...more].forEach(([c, m, cat, u, e, d]) => C(c, m, cat, u, e, d));

// Bulk generate more chunks to reach 1000+
// Generate patterns for 600+ more chunks
const bulkDaily = [
"all set","准备好了","daily","一切都准备好了","Everything is packed — we're all set to go.","beginner",
"any minute now","马上随时","daily","很快就会发生","The bus should be here any minute now.","beginner",
"as far as I know","据我所知","daily","基于现有信息","As far as I know the meeting is still on.","beginner",
"at the drop of a hat","毫不犹豫","daily","立刻毫不迟疑","She'd move abroad at the drop of a hat.","advanced",
"be my guest","请便","daily","邀请对方随意使用","Can I use your phone? — Be my guest!","beginner",
"behind the times","落后于时代","daily","跟不上时代","His teaching methods are behind the times.","intermediate",
"better safe than sorry","安全总比后悔好","daily","宁愿小心谨慎","Take an umbrella — better safe than sorry.","beginner",
"bide your time","等待时机","daily","耐心等待机会","He's biding his time until the right opportunity.","advanced",
"bite off more than you can chew","贪多嚼不烂","daily","接下太多做不完","I bit off more than I could chew with 3 projects.","intermediate",
"blow your top","勃然大怒","daily","突然非常生气","Dad blew his top when he saw the mess.","intermediate",
"bottom of the barrel","最差的","daily","已经没好的可选了","This candidate is really the bottom of the barrel.","advanced",
"break a sweat","费很大劲","daily","花费很多力气","He fixed the car without even breaking a sweat.","intermediate",
"breathe down someone's neck","紧盯着某人","daily","过度监视","My boss keeps breathing down my neck.","advanced",
"bright and early","一大清早","daily","非常早起床","We have to leave bright and early tomorrow.","beginner",
"bring home the bacon","养家糊口","daily","赚钱养家","She works two jobs to bring home the bacon.","intermediate",
"brush up on","温习提高","daily","复习某个技能","I need to brush up on my Spanish before the trip.","intermediate",
"build castles in the air","做白日梦","daily","不切实际的幻想","Stop building castles in the air and make a real plan.","advanced",
"bump into","偶遇","daily","意外碰见某人","I bumped into my old teacher at the mall.","beginner",
"bundle of nerves","紧张不安","daily","非常紧张的人","Before the speech I was a bundle of nerves.","intermediate",
"burn a hole in your pocket","口袋里留不住钱","daily","一有钱就想花掉","That bonus is burning a hole in his pocket.","advanced",
"call it a night","今晚到此为止","daily","结束晚上的活动","It's late — let's call it a night.","beginner",
"call the tune","定调子做主","daily","处于掌控地位","Whoever pays the piper calls the tune.","advanced",
"can't complain","没什么可抱怨的","daily","过得还行","How's work? — Can't complain.","beginner",
"carry a tune","音准好会唱歌","daily","唱歌不跑调","I can't carry a tune to save my life.","intermediate",
"catch some Zs","睡一觉","daily","去睡觉","I'm beat — I need to catch some Zs.","beginner",
"change your tune","改变态度","daily","态度从反对变支持","He changed his tune when he saw the profits.","intermediate",
"chicken out","临阵退缩","daily","因害怕而退出","I was going to skydive but I chickened out.","intermediate",
"clear the decks","清理准备","daily","为某事做好准备","Let's clear the decks before the big meeting.","advanced",
"come in handy","派上用场","daily","在未来有用","Save that box — it might come in handy later.","beginner",
"come to your senses","恢复理智","daily","清醒过来","He finally came to his senses and quit that job.","intermediate",
"come what may","无论发生什么","daily","不管怎样都坚持","I'll support you come what may.","advanced",
"cook up a storm","做一大桌菜","daily","大量做饭","She cooked up a storm for the family reunion.","intermediate",
"cost an arm and a leg","贵得离谱","daily","非常昂贵","That designer bag costs an arm and a leg.","intermediate",
"couch potato","沙发土豆","daily","总窝在沙发上看电视的人","He's turned into a real couch potato lately.","intermediate",
"crack of dawn","破晓时分","daily","一大清早","We woke up at the crack of dawn to catch our flight.","beginner",
"crash course","速成课","daily","快速学习课程","I took a crash course in Excel before the job.","intermediate",
"creature of habit","习惯性生物","daily","按习惯生活的人","I'm a creature of habit — same breakfast every day.","intermediate",
"cross my mind","在我脑海中闪过","daily","突然想到","It never crossed my mind that he might be lying.","intermediate",
"cruise control","轻松自如","daily","轻松不用太费力的状态","After the first month the job was on cruise control.","intermediate",
"curiosity killed the cat","好奇害死猫","daily","警告不要过于好奇","Don't ask too many questions — curiosity killed the cat.","intermediate",
"cut the cord","切断联系","daily","摆脱依赖","It's time to cut the cord and move out.","intermediate",
"daylight robbery","明抢","daily","价格贵得离谱","Ten dollars for a bottle of water is daylight robbery.","advanced",
"dead end","死胡同","daily","没有出路","This street is a dead end — we need to turn around.","beginner",
"devil is in the details","魔鬼在细节中","daily","细节决定成败","The plan looks good but the devil is in the details.","advanced",
"dirt cheap","非常便宜","daily","极其廉价","I got this jacket dirt cheap at the thrift store.","intermediate",
"dodge a bullet","躲过一劫","daily","侥幸避开了坏事","That company went bankrupt after I quit — dodged a bullet.","intermediate",
"donkey work","苦力活","daily","繁重单调的工作","The interns do all the donkey work around here.","advanced",
"double-check","再检查一次","daily","确认无误","Double-check the address before you send it.","beginner",
"drag your feet","拖拖沓沓","daily","故意拖延","Stop dragging your feet and finish the report!","intermediate",
"dressed to kill","盛装打扮","daily","穿得非常好看","She was dressed to kill at the gala.","intermediate",
"drive a hard bargain","狠砍价","daily","谈判中不让步","He drives a hard bargain — we barely made a profit.","intermediate",
"drop in the ocean","杯水车薪","daily","九牛一毛","The donation was just a drop in the ocean.","advanced",
"Dutch courage","酒后壮胆","daily","喝酒壮胆","He needed some Dutch courage before asking her out.","advanced",
"earful","一顿臭骂","daily","被狠狠批评","I got an earful from the boss for being late again.","intermediate",
"egg on your face","丢脸难堪","daily","出丑尴尬","He had egg on his face after his prediction was wrong.","intermediate",
"elbow room","活动空间","daily","足够的空间","This apartment is nice but there's not much elbow room.","intermediate",
"eleventh hour","最后一刻","daily","截止前最后关头","They reached an agreement at the eleventh hour.","intermediate",
"enough is enough","够了忍无可忍","daily","不能再容忍了","Enough is enough — I'm filing a complaint.","beginner",
"err on the side of caution","谨慎行事","daily","选择更安全的方式","Let's err on the side of caution and bring extra supplies.","advanced",
"every nook and cranny","每个角落","daily","每一处缝隙","We searched every nook and cranny for the missing ring.","advanced",
"fair and square","光明正大的","daily","诚实公平赢得的","We won the game fair and square — no cheating.","intermediate",
"fall into place","水到渠成","daily","事情自然变得顺利","Once she joined the team everything fell into place.","intermediate",
"far cry from","差距很大","daily","与某事相差甚远","This apartment is a far cry from what I expected.","advanced",
"fast asleep","熟睡","daily","睡得很沉","The baby was fast asleep within minutes.","beginner",
"feather in your cap","一项成就","daily","值得骄傲的成就","Getting that award was a real feather in his cap.","advanced",
"feel the pinch","感到拮据","daily","经济紧张","With rising prices everyone is feeling the pinch.","intermediate",
"few and far between","稀少罕见","daily","非常不常见","Honest mechanics are few and far between these days.","advanced",
"fire in your belly","满腔热情","daily","很有热情和动力","She's got fire in her belly — she'll go far.","advanced",
"first things first","先做最重要的","daily","按优先顺序来","First things first — let's address the safety issue.","beginner",
"fit the bill","符合要求","daily","满足条件","This candidate really fits the bill — hire her.","intermediate",
"flash in the pan","昙花一现","daily","短暂的一时成功","Their first hit was a flash in the pan.","advanced",
"flat out","全力地","daily","以最快速度","I've been working flat out all week.","intermediate",
"flesh and blood","血肉之亲","daily","有血有肉的家人","He's my flesh and blood — I can't abandon him.","intermediate",
"flog a dead horse","鞭打死马","daily","白费力气","Trying to change his mind is flogging a dead horse.","advanced",
"fly in the ointment","美中不足","daily","唯一的缺陷","The fly in the ointment is the long commute.","advanced",
"follow your nose","跟着直觉走","daily","凭直觉行动","Just follow your nose — you'll find the bakery.","beginner",
"food for thought","引人深思","daily","值得思考的内容","That documentary gave me a lot of food for thought.","intermediate",
"fool's paradise","愚人天堂","daily","虚假的幸福","He's living in a fool's paradise if he thinks she's coming back.","advanced",
"foot in the door","入门第一步","daily","获得初步机会","The internship gave her a foot in the door.","intermediate",
"for the time being","暂时","daily","目前这个阶段","For the time being just keep doing what you're doing.","intermediate",
"force of habit","习惯使然","daily","出于习惯的行为","I woke up at 6am by force of habit even on Sunday.","intermediate",
"fortune favors the bold","幸运眷顾勇者","daily","勇敢才能得到好运","Take the risk — fortune favors the bold.","advanced",
"free as a bird","自由如鸟","daily","完全自由","After quitting I felt free as a bird.","intermediate",
"fresh as a daisy","神清气爽","daily","精神焕发","After a good night's sleep I feel fresh as a daisy.","intermediate",
"full of yourself","自以为是","daily","过于自负","He's so full of himself — always bragging.","intermediate",
"get a grip","控制住自己","daily","冷静下来控制情绪","Get a grip — it's not the end of the world!","intermediate",
"get off my back","别烦我","daily","别再唠叨我","Get off my back — I'll do it when I'm ready!","intermediate",
"get the picture","明白理解","daily","理解了情况","I get the picture — you don't want to go.","beginner",
"get wind of","听到风声","daily","听说某事","Did you get wind of the layoffs coming?","intermediate",
"give the benefit of the doubt","暂且相信","daily","在没有证据时选择相信","I'll give him the benefit of the doubt this time.","intermediate",
"go belly up","破产倒闭","daily","企业失败","The restaurant went belly up after just six months.","advanced",
"go down in flames","轰轰烈烈失败","daily","壮烈失败","His plan went down in flames at the board meeting.","advanced",
"go figure","想不通真奇怪","daily","对奇怪事情的感叹","He quit his high-paying job to become a clown — go figure.","intermediate",
"go off on a tangent","离题跑题","daily","突然转到无关话题","He went off on a tangent about his vacation.","advanced",
"go out on a limb","冒风险","daily","做有风险的事","I'm going out on a limb here — but I think she's wrong.","advanced",
"go to great lengths","竭尽全力","daily","付出极大努力","She went to great lengths to make us feel welcome.","intermediate",
"golden opportunity","黄金机会","daily","极好不容错过的机会","This scholarship is a golden opportunity — apply now!","intermediate",
"good riddance","走得好","daily","幸好人或事离开了","He finally quit? Good riddance I say!","intermediate",
"grab a bite","随便吃点","daily","快速吃点东西","Want to grab a bite before the movie?","beginner",
"grasping at straws","抓救命稻草","daily","绝望中胡乱尝试","He's grasping at straws trying to explain the failure.","advanced",
"grease the wheels","疏通关系","daily","让事情更顺滑地进行","A small gift helped grease the wheels with customs.","advanced",
"green light","绿灯放行","daily","批准许可做某事","We got the green light to start construction.","beginner",
"ground rules","基本规则","daily","大家要遵守的基础规则","Let's set some ground rules before we start.","intermediate",
"grunt work","枯燥的基础工作","daily","无聊但必要的工作","The interns handle the grunt work like data entry.","intermediate",
"guilty pleasure","罪恶的小乐趣","daily","不好意思但喜欢的事","Watching reality TV is my guilty pleasure.","intermediate",
"gut instinct","直觉本能","daily","不经思考的第一反应","My gut instinct says this deal is too good to be true.","intermediate",
"hair-raising","毛骨悚然的","daily","非常恐怖刺激","It was a hair-raising ride on the mountain road.","intermediate",
"hand over fist","快速大量地","daily","迅速地赚或花很多钱","They were making money hand over fist during the boom.","advanced",
"hang by a thread","岌岌可危","daily","处于非常脆弱的状态","The peace agreement is hanging by a thread.","advanced",
"hard pill to swallow","难以下咽的苦果","daily","难以接受的现实","Losing the final was a hard pill to swallow.","advanced",
"harden your heart","心肠变硬","daily","不再有同情心","She hardened her heart and refused to help.","advanced",
"harp on about","喋喋不休","daily","反复提同一件事","Stop harping on about your ex — it's been months.","intermediate",
"haste makes waste","欲速则不达","daily","太快做事容易出错","Slow down — haste makes waste.","intermediate",
"haul over the coals","严厉批评","daily","被狠狠地训斥","The manager hauled him over the coals for the mistake.","advanced",
"have a go","试一下","daily","尝试做某事","Let me have a go at fixing the sink.","beginner",
"have a say","有发言权","daily","在决策中有话语权","I want to have a say in how the money is spent.","intermediate",
"head in the clouds","不切实际","daily","心不在焉做白日梦","He's got his head in the clouds — needs to focus.","intermediate",
"head start","先发优势","daily","有利的早期起点","Her internship gave her a head start in her career.","intermediate",
"hear on the grapevine","小道消息听说","daily","通过非正式渠道听到","I heard on the grapevine that they're getting married.","advanced",
"heart in the right place","本意是好的","daily","意图善良","His heart is in the right place even if his methods are wrong.","intermediate",
"heart of gold","金子般的心","daily","非常善良的人","She may seem tough but she has a heart of gold.","intermediate",
"heavy going","艰难费力的","daily","进展困难","The book is heavy going in the first few chapters.","intermediate",
"hedge your bets","对冲风险","daily","两面下注降低风险","Invest in different sectors to hedge your bets.","advanced",
"here and now","此时此地","daily","现在这一刻","Make a decision in the here and now — don't wait.","intermediate",
"hidden agenda","隐藏的意图","daily","不公开的真实目的","I suspect he has a hidden agenda behind his offer.","advanced",
"high and dry","孤立无援","daily","被抛下得不到帮助","Her colleagues quit and left her high and dry.","intermediate",
"high time","该是时候了","daily","早就应该做某事了","It's high time you started taking your health seriously.","intermediate",
"hit the ground running","立即开始高效工作","daily","从第一天就高效","We need someone who can hit the ground running.","intermediate",
"hold the fort","临时看管","daily","暂时代管","Can you hold the fort while I'm at lunch?","intermediate",
"hook line and sinker","完全相信","daily","彻底上当被骗","He fell for the scam hook line and sinker.","advanced",
"hot under the collar","愤怒烦躁的","daily","因为生气而烦躁","He gets hot under the collar whenever I mention politics.","intermediate",
"hustle and bustle","忙忙碌碌","daily","城市的热闹繁忙气氛","I love the hustle and bustle of big cities.","intermediate",
"in a tight spot","处于困境","daily","面临困难","Can you lend me some money? I'm in a tight spot.","intermediate",
"in broad daylight","光天化日之下","daily","公开地在白天","The thief stole the bike in broad daylight.","intermediate",
"in hot water","陷于麻烦","daily","有麻烦了","He's in hot water with his boss for missing the deadline.","intermediate",
"in the bag","稳操胜券","daily","十拿九稳已经赢定了","With that lead the game is in the bag.","intermediate",
"in the blink of an eye","瞬间一眨眼","daily","非常快的一瞬间","The tornado destroyed the town in the blink of an eye.","intermediate",
"in the same boat","处境相同","daily","面临相同的困难","We're all in the same boat — don't worry.","intermediate",
"in two minds","犹豫不决","daily","在两个选择间摇摆","I'm in two minds about accepting the offer.","intermediate",
"ins and outs","方方面面","daily","所有细节和复杂性","It takes time to learn the ins and outs of the company.","intermediate",
"iron fist in a velvet glove","外柔内刚","daily","表面温和内心强硬","She leads with an iron fist in a velvet glove.","advanced",
"jack of all trades","样样通但样样不精","daily","什么都会一点但都不精通","He's a jack of all trades — can fix almost anything.","intermediate",
"jump for joy","高兴得跳起来","daily","非常兴奋","The kids jumped for joy when they saw the puppy.","beginner",
"just around the corner","即将到来","daily","马上就要发生","Spring is just around the corner — hang in there.","beginner",
"just what the doctor ordered","正是需要的","daily","刚好需要的东西","This vacation is just what the doctor ordered.","intermediate",
"keep a low profile","保持低调","daily","不引人注意","Let's keep a low profile until the controversy blows over.","intermediate",
"keep body and soul together","勉强维生","daily","能勉强度日","The salary is barely enough to keep body and soul together.","advanced",
"keep your cool","保持冷静","daily","不失去冷静","Even when provoked she managed to keep her cool.","intermediate",
"keep your fingers crossed","交叉手指祈求好运","daily","希望一切顺利","Keep your fingers crossed — the results come out today.","beginner",
"keep your hair on","别发火","daily","冷静别生气","Keep your hair on — it was just a joke!","intermediate",
"keep your head above water","勉强维持","daily","能维持不溺水","I'm just barely keeping my head above water with bills.","intermediate",
"keep your shirt on","别急沉住气","daily","让对方保持冷静","Keep your shirt on — I'm coming!","intermediate",
"keyed up","紧张兴奋","daily","亢奋的状态","I was all keyed up before the big presentation.","intermediate",
"kick in the teeth","重大打击","daily","突然的重大挫折","Getting rejected was a real kick in the teeth.","advanced",
"kick up your heels","放松享受","daily","好好玩乐","Let's kick up our heels this weekend!","intermediate",
"kill the fatted calf","设宴款待","daily","隆重招待来客","When their son returned home they killed the fatted calf.","advanced",
"knock on wood","敲木头以防厄运","daily","希望好运继续","I've never had an accident — knock on wood.","intermediate",
"knock yourself out","随意请便","daily","让对方尽管去做","Want to try to fix it yourself? Knock yourself out.","intermediate",
"know inside out","了如指掌","daily","完全彻底了解","She knows this industry inside out.","intermediate",
"know which way the wind blows","了解风向","daily","敏锐了解趋势变化","He knows which way the wind blows in politics.","advanced",
"labor of love","为爱而做的事","daily","出于热爱而非报酬做的事","This garden is a labor of love — I spend every weekend on it.","intermediate",
"laughing stock","笑柄","daily","被众人嘲笑的对象","After that blunder he became the laughing stock of the office.","intermediate",
"lay it on thick","说得过重夸张","daily","夸大其词或过分奉承","She was laying it on thick with all the compliments.","advanced",
"lead the way","带路引领","daily","带头走在前面","You know the area best — lead the way.","beginner",
"leave a bad taste in your mouth","留下糟糕的印象","daily","让人感到不舒服","The way he treated her left a bad taste in my mouth.","advanced",
"leave high and dry","弃之不顾","daily","突然抛下让人孤立无援","The contractor left us high and dry with a half-finished house.","intermediate",
"leave no stone unturned","不遗余力","daily","彻底做尽一切可能","The detectives left no stone unturned in the case.","advanced",
"leave well enough alone","别画蛇添足","daily","已经挺好的了别乱改","It works fine — just leave well enough alone.","intermediate",
"let bygones be bygones","让过去的事过去吧","daily","不再纠结过去","We agreed to let bygones be bygones and start fresh.","advanced",
"let the chips fall where they may","随它去吧","daily","不管后果如何","I'm going to tell the truth and let the chips fall where they may.","advanced",
"lick your wounds","舔舐伤口","daily","失败后恢复休整","After the defeat the team went home to lick their wounds.","advanced",
"life of the party","聚会中的灵魂人物","daily","聚会中最活跃的人","Jim is always the life of the party — so funny and energetic.","intermediate",
"light at the end of the tunnel","隧道尽头的曙光","daily","困境中的希望","Finally we can see the light at the end of the tunnel.","intermediate",
"like two peas in a pod","一模一样","daily","两人极其相似","The twins are like two peas in a pod.","intermediate",
"lion's share","最大的一部分","daily","份额中的大部分","She did the lion's share of the work on the project.","advanced",
"live beyond your means","入不敷出","daily","花钱超过收入","They've been living beyond their means for years.","intermediate",
"load of rubbish","一堆废话","daily","完全是胡说","That article is a load of rubbish — don't believe it.","intermediate",
"long haul","持久的过程","daily","需要长期坚持的事","Learning a language is a long haul but worth it.","intermediate",
"lose your touch","技艺生疏","daily","不再擅长曾擅长的事","He used to be a great chef but he's lost his touch.","intermediate",
"maiden voyage","处女航","daily","首次出行或使用","The ship sank on its maiden voyage.","advanced",
"make a clean breast of","坦白承认","daily","完全坦白","He made a clean breast of his mistakes to the board.","advanced",
"make a comeback","东山再起","daily","重新成功","After years of obscurity the band made a huge comeback.","intermediate",
"make a killing","大赚一笔","daily","赚了很多钱","They made a killing in the stock market.","intermediate",
"make do with","凑合用","daily","将就用已有的东西","We'll have to make do with what we have.","intermediate",
"make hay while the sun shines","趁热打铁","daily","抓住好时机","Interest rates are low — make hay while the sun shines.","advanced",
"make light of","不当回事","daily","把重要问题看得太轻","Don't make light of her concerns — they're real.","intermediate",
"make no bones about","毫不掩饰","daily","直言不讳表达","She made no bones about her dislike of the proposal.","advanced",
"make your blood run cold","让你毛骨悚然","daily","极其恐怖","The scream made my blood run cold.","intermediate",
"man of his word","言而有信的人","daily","说话算数的人","He's a man of his word — if he promised he'll deliver.","intermediate",
"march to the beat of your own drum","按自己的步调走","daily","做自己不在乎别人","She's always marched to the beat of her own drum.","advanced",
"matter of life and death","生死攸关","daily","极其重要","Finding the medicine was a matter of life and death.","intermediate",
"meet your match","碰到对手","daily","遇到跟你实力相当的人","He finally met his match in the chess tournament.","intermediate",
"mess with the wrong person","惹错了人","daily","惹了不该惹的人","You're messing with the wrong person — she's the CEO.","intermediate",
"method to my madness","看似疯狂其实有道理","daily","看似无逻辑但背后有原因","I know it looks chaotic but there's method to my madness.","advanced",
"miles away","心不在焉","daily","走神了没注意听","Sorry, I was miles away — what did you say?","intermediate",
"mind over matter","精神战胜物质","daily","意志力克服身体困难","Mind over matter — you can push through the pain.","intermediate",
"miss the forest for the trees","只见树木不见森林","daily","只见细节不见全局","Stop obsessing over details — you're missing the forest for the trees.","advanced",
"moment of truth","关键时刻","daily","决定性的考验时刻","The moment of truth has arrived — time for the presentation.","intermediate",
"money doesn't grow on trees","钱不是天上掉下来的","daily","钱来之不易","No you can't have a new phone — money doesn't grow on trees.","beginner",
"more than meets the eye","不止表面看到的","daily","比看起来更深刻","There's more to this case than meets the eye.","intermediate",
"mountain out of a molehill","小题大做","daily","把小事夸张成大事","It's a minor typo — don't make a mountain out of a molehill.","intermediate",
"mover and shaker","有影响力的人","daily","能推动变化的人","She's one of the movers and shakers in the tech industry.","advanced",
"much of a muchness","大同小异","daily","都差不多没什么区别","All the candidates were much of a muchness.","advanced",
"muddy the waters","把水搅浑","daily","让事情更复杂更混乱","His vague explanation only muddied the waters further.","advanced",
"mum's the word","保密的","daily","不要告诉别人","Mum's the word about the birthday surprise.","intermediate",
"music to my ears","听起来太好了","daily","听到开心的话","When they said I got the job it was music to my ears.","intermediate",
"neck of the woods","这附近的区域","daily","指某个地区或附近","I haven't seen you in this neck of the woods before.","intermediate",
"needle in a haystack","大海捞针","daily","在大量事物中找一个东西","Finding the key in the sand was like a needle in a haystack.","intermediate",
"nest egg","储备金","daily","为将来存的钱","They've built up a nice nest egg for retirement.","intermediate",
"never say never","别说不","daily","任何事情都有可能","I'll never move back — well, never say never.","intermediate",
"new kid on the block","新来的","daily","新加入的成员","As the new kid on the block I was nervous at first.","intermediate",
"nice touch","点睛之笔","daily","贴心的好细节","The handwritten thank-you note was a nice touch.","intermediate",
"nickel and dime","小事上抠门","daily","在小钱上斤斤计较","The airline nickels and dimes you for every little thing.","advanced",
"night owl","夜猫子","daily","晚睡的人","I'm a night owl — most productive after 10pm.","beginner",
"no dice","不行没门","daily","被拒绝或不可行","I asked for a raise but it was no dice.","intermediate",
"no love lost","互不喜欢","daily","两人互相看不顺眼","There's no love lost between those two rivals.","advanced",
"no strings attached","没有附加条件","daily","无条件无捆绑","They offered me the job with no strings attached.","intermediate",
"no sweat","没问题很轻松","daily","不费劲很简单","Can you help me? — No sweat!","beginner",
"nose around","到处打听","daily","到处探听消息","Someone has been nosing around asking about our finances.","intermediate",
"not born yesterday","不傻不天真","daily","不是容易上当的","Of course I know he's lying — I wasn't born yesterday.","intermediate",
"nothing to write home about","没什么特别的","daily","不值得特别提及","The food was okay but nothing to write home about.","intermediate",
"now you're talking","这才像话","daily","终于说出了好建议","Pizza for dinner? Now you're talking!","intermediate",
"nuts and bolts","基本组成部分","daily","核心实用的细节","Let's get down to the nuts and bolts of the contract.","intermediate",
"off the beaten track","偏僻的","daily","远离常规路线","We found this hidden beach off the beaten track.","intermediate",
"off the hook","脱身了","daily","免于惩罚或免于麻烦","The evidence cleared him so he's off the hook.","intermediate",
"off the wall","古怪疯癫的","daily","特别奇怪的想法","His ideas are always a bit off the wall.","intermediate",
"old habits die hard","旧习难改","daily","老习惯不容易改变","I still check my work email on vacation — old habits die hard.","intermediate",
"on a silver platter","唾手可得","daily","没有付出努力就得到","He expects everything to be handed to him on a silver platter.","intermediate",
"on cloud nine","在九重天上","daily","极度欢欣","She's been on cloud nine ever since the engagement.","intermediate",
"on its last legs","快不行了","daily","濒临报废或死亡","My laptop is on its last legs — I need a new one.","intermediate",
"on second thought","转念一想","daily","改变了之前的想法","On second thought maybe I'll stay home tonight.","beginner",
"on the bright side","往好的方面看","daily","从积极角度看","On the bright side the rain is good for the garden.","beginner",
"on the cards","很可能发生的","daily","在未来很有可能","A promotion might be on the cards if we land this client.","intermediate",
"on the house","免费赠送的","daily","由商家买单","These drinks are on the house — enjoy!","beginner",
"on the same wavelength","想法一致","daily","思维频率相同","We're on the same wavelength — I was about to suggest that.","intermediate",
"on the spot","当场立刻","daily","当时当地马上就","They offered her the job on the spot.","intermediate",
"on thin ice","如履薄冰","daily","处于危险的边界","After three warnings he's skating on thin ice.","intermediate",
"one in a million","万里挑一","daily","非常独特极其稀有","My wife is one in a million — I'm so lucky.","intermediate",
"open a can of worms","捅马蜂窝","daily","引发一系列麻烦","Mentioning the budget opened a can of worms at the meeting.","advanced",
"open secret","公开的秘密","daily","大家心知肚明但不说的事","Their affair was an open secret in the office.","intermediate",
"out of sight out of mind","眼不见心不烦","daily","看不见就容易忘记","Once I moved away we drifted apart — out of sight out of mind.","intermediate",
"out of sorts","不太对劲","daily","感觉不太舒服或略烦躁","I'm feeling a bit out of sorts today — might be catching a cold.","intermediate",
"out of the frying pan into the fire","刚脱离虎口又入狼窝","daily","从一个困境跳入更糟的困境","Leaving that job for a worse one is out of the frying pan into the fire.","advanced",
"out of this world","好得不得了","daily","极其出色","This chocolate cake is out of this world!","intermediate",
"out of whack","不正常","daily","功能失调不平衡","The budget numbers are out of whack — something's off.","intermediate",
"out on a limb","孤立无援","daily","独自冒险","I went out on a limb to support your proposal.","intermediate",
"over and done with","结束了的","daily","彻底完成不再需要考虑","I'm glad the exam is over and done with.","intermediate",
"over my dead body","除非我死了","daily","坚决不允许发生","You want to marry him? Over my dead body!","intermediate",
"packed like sardines","挤得像罐头里的沙丁鱼","daily","非常拥挤","The subway was packed like sardines during rush hour.","intermediate",
"paddle your own canoe","自力更生","daily","自己独立搞定","Time to paddle your own canoe — I can't help anymore.","advanced",
"par for the course","意料之中","daily","这种情况下的常态","Delays are par for the course in construction.","intermediate",
"pass the buck","踢皮球推卸责任","daily","把责任推给别人","He always passes the buck instead of taking responsibility.","advanced",
"pat on the back","表扬鼓励","daily","肯定和赞许","You deserve a pat on the back for all your hard work.","intermediate",
"pay through the nose","花大价钱","daily","付了过高的钱","We paid through the nose for those concert tickets.","intermediate",
"pecking order","啄食顺序","daily","群体中的等级排序","The new guy is at the bottom of the pecking order.","advanced",
"penny for your thoughts","你在想什么","daily","问对方在想什么","You're very quiet — penny for your thoughts?","intermediate",
"pep talk","鼓舞士气的话","daily","激励人的简短谈话","The coach gave us a great pep talk before the game.","intermediate",
"pick up the pieces","收拾残局","daily","灾后复原重新开始","After the divorce she had to pick up the pieces.","intermediate",
"pin down","按住确认","daily","搞清楚确认细节","I can't pin him down on a specific date.","intermediate",
"pipe dream","白日梦","daily","不可能实现的梦想","Owning a private jet is just a pipe dream for most people.","intermediate",
"plain sailing","一帆风顺","daily","一切顺利没有困难","Once we got the permit it was plain sailing.","intermediate",
"play second fiddle","当副手配角","daily","居于次要地位","I'm tired of playing second fiddle to his ideas.","advanced",
"play with fire","玩火自焚","daily","做危险的事","You're playing with fire by lying to the boss.","intermediate",
"point of no return","不归路","daily","无法回头的地步","Once the contract is signed we're past the point of no return.","advanced",
"pop the question","求婚","daily","问是否愿意结婚","He popped the question during a romantic dinner.","intermediate",
"pot calling the kettle black","五十步笑百步","daily","指责别人做自己也在做的事","You're calling me lazy? That's the pot calling the kettle black.","advanced",
"pour cold water on","泼冷水","daily","打击某个想法或提议","She poured cold water on my plan to start a business.","intermediate",
"press the panic button","按下恐慌按钮","daily","过度反应陷入恐慌","Let's not press the panic button — it's just a small setback.","intermediate",
"pros and cons","利与弊","daily","正反两方面的分析","Let's weigh the pros and cons before deciding.","intermediate",
"pull a fast one","耍花招","daily","欺骗或使诈","Don't try to pull a fast one — I'm watching you.","intermediate",
"pull out all the stops","全力以赴","daily","尽一切可能做到最好","They pulled out all the stops for the anniversary party.","advanced",
"pull the wool over someone's eyes","蒙骗某人","daily","让人看不清真相","He tried to pull the wool over my eyes but I knew better.","advanced",
"pull yourself together","振作起来","daily","从情绪中恢复","Pull yourself together — we have work to do.","intermediate",
"push comes to shove","到了关键时刻","daily","在最后不得不行动时","If push comes to shove we'll sell the car.","advanced",
"put on a brave face","装作勇敢","daily","在困难面前表现坚强","She put on a brave face despite the bad news.","intermediate",
"put someone on the spot","让某人难做","daily","当场让人尴尬或做决定","You put me on the spot asking about my salary.","intermediate",
"put the brakes on","刹车叫停","daily","减慢或停止某事","We need to put the brakes on spending until next month.","intermediate",
"put your money where your mouth is","实际行动起来","daily","说到做到拿出行动","If you believe in it put your money where your mouth is.","intermediate",
"put your thinking cap on","认真思考","daily","开始认真想问题","Put your thinking cap on — we need a creative solution.","intermediate",
"quick off the mark","反应快","daily","迅速反应的人","She was quick off the mark and got the best deals.","intermediate",
"rain on someone's parade","泼冷水扫兴","daily","破坏别人的兴致","I hate to rain on your parade but there's a problem.","intermediate",
"raise eyebrows","引起侧目","daily","让人吃惊或不满","His casual attire raised a few eyebrows at the formal dinner.","intermediate",
"read the riot act","严厉警告","daily","大声斥责","The boss read him the riot act for being late again.","advanced",
"recharge your batteries","充电恢复","daily","休息以恢复精力","I need a vacation to recharge my batteries.","intermediate",
"red flag","危险信号","daily","警告有问题的迹象","His refusal to answer questions was a major red flag.","intermediate",
"reinvent the wheel","重复发明轮子","daily","没必要重新做已有的东西","Don't reinvent the wheel — use the existing template.","intermediate",
"rhyme or reason","道理","daily","任何逻辑或意义","There's no rhyme or reason to his decision.","intermediate",
"right as rain","一切都好","daily","状态良好","After a nap she was right as rain again.","intermediate",
"right off the bat","一开始","daily","从一开始就","I liked him right off the bat — he was so friendly.","intermediate",
"rob Peter to pay Paul","拆东墙补西墙","daily","借新债还旧债","Using one credit card to pay another is robbing Peter to pay Paul.","advanced",
"rock the boat","惹麻烦捣乱","daily","破坏安稳","Don't rock the boat — things are finally going smoothly.","intermediate",
"roll out the red carpet","隆重欢迎","daily","铺上红地毯热情欢迎","The hotel really rolled out the red carpet for us.","intermediate",
"rub salt in the wound","伤口上撒盐","daily","让痛苦的人更难受","Talking about his ex was rubbing salt in the wound.","intermediate",
"rule the roost","主宰","daily","处于支配地位","In this household grandma rules the roost.","advanced",
"safety net","安全网保障","daily","以防万一的后备方案","Savings provide a safety net in case of job loss.","intermediate",
"salt of the earth","社会中坚","daily","诚实可靠的人","They're the salt of the earth — kind and hardworking.","advanced",
"save face","挽回面子","daily","维持体面尊严","He apologized to save face after the argument.","intermediate",
"scratch the surface","表面","daily","只是了解皮毛","We've only scratched the surface of what AI can do.","intermediate",
"seal of approval","认可的印章","daily","正式批准和认可","The project got the CEO's seal of approval.","intermediate",
"see red","非常愤怒","daily","被激得暴怒","When he insulted my family I just saw red.","intermediate",
"set in your ways","固守自己的习惯","daily","习惯固化不愿改变","My dad is very set in his ways — won't try new food.","intermediate",
"shape up or ship out","要么改进要么走人","daily","不改进就会被淘汰","The new manager told us to shape up or ship out.","advanced",
"sharp as a tack","非常聪明","daily","极其敏锐机灵","My grandmother is 90 but still sharp as a tack.","intermediate",
"shed light on","照亮揭示","daily","帮助理解或澄清某事","Can you shed some light on why the project was canceled?","intermediate",
"shoot from the hip","不假思索就说","daily","鲁莽直率说话","He tends to shoot from the hip — doesn't think before speaking.","advanced",
"short and sweet","简短而令人愉快","daily","简练但很好的","The meeting was short and sweet — only 15 minutes.","beginner",
"shot in the dark","瞎猜","daily","没有任何把握的猜测","My answer was just a shot in the dark — pure luck.","intermediate",
"sight for sore eyes","见到你真高兴","daily","看到想见的人时的感叹","You're a sight for sore eyes — I missed you!","intermediate",
"sink or swim","要么沉要么游","daily","靠自己的能力或成功或失败","They threw me in and said sink or swim.","intermediate",
"sixth sense","第六感","daily","超越五感的直觉","My sixth sense told me something was wrong.","intermediate",
"skeleton in the closet","脏事","daily","不可告人的秘密","Every politician has skeletons in the closet.","advanced",
"slap on the wrist","轻微处罚","daily","微不足道的警告","He only got a slap on the wrist for stealing.","intermediate",
"small world","世界真小","daily","巧合感叹","You know Sarah too? What a small world!","beginner",
"smooth sailing","一风顺遂","daily","进展顺利没有问题","After the initial hiccup it was smooth sailing.","intermediate",
"snail mail","普通邮寄","daily","纸质邮件（相对于电子邮件）","The package will arrive by snail mail in about a week.","intermediate",
"so far so good","目前来看还不错","daily","到目前为止一切顺利","How's the project going? — So far so good.","beginner",
"speak of the devil","说曹操曹操到","daily","谈到某人就出现","Speak of the devil — we were just talking about you!","intermediate",
"spitting image","长得一模一样","daily","完全相像","She's the spitting image of her mother.","intermediate"
];
// End of bulk data

// Process bulk daily
for (let i = 0; i < bulkDaily.length; i += 6) {
  const [c, m, cat, u, e, d] = bulkDaily.slice(i, i+6);
  C(c, m, cat, u, e, d);
}

console.log(`Total chunks generated: ${chunks.length}`);

// Write the TypeScript file
let ts = '// EXPORTS: IChunk, MOCK_CHUNKS\n';
ts += 'export interface IChunk {\n';
ts += '  id: string; content: string; meaning: string;\n';
ts += '  category: \"daily\" | \"workplace\" | \"social\" | \"emotion\";\n';
ts += '  usage: string; example: string;\n';
ts += '  difficulty: \"beginner\" | \"intermediate\" | \"advanced\";\n';
ts += '}\n\n';
ts += 'export const MOCK_CHUNKS: IChunk[] = [\n';

for (const item of chunks) {
  const esc = (s) => s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  ts += "  { id:'" + item.id + "', content:'" + esc(item.content) + "', meaning:'" + esc(item.meaning) + "', category:'" + item.category + "', usage:'" + esc(item.usage) + "', example:'" + esc(item.example) + "', difficulty:'" + item.difficulty + "' },\n";
}

ts += '];\n';
fs.writeFileSync('src/data/chunks.ts', ts);
console.log(`Written ${chunks.length} chunks to chunks.ts`);
