/**
 * Generate IWordEntry[] .ts files from KyleBing/english-vocabulary JSON.
 *
 * Usage: npx tsx scripts/generate-wordbank.ts
 *
 * KyleBing JSON format:
 *   [{ word, translations: [{ translation, type }], phrases: [{ phrase, translation }] }]
 *
 * Output: src/data/wordbank/data/{level}.ts — IWordEntry[] export
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const DATA_DIR = path.resolve(__dirname, '../src/data/wordbank/data');

const SOURCES: { key: string; url: string; label: string; topics: string[] }[] = [
  {
    key: 'zhongkao',
    url: 'https://raw.githubusercontent.com/KyleBing/english-vocabulary/master/%E5%88%9D%E4%B8%AD-%E9%A1%BA%E5%BA%8F.json',
    label: 'zhongkao',
    topics: ['examination', 'middle_school'],
  },
  {
    key: 'gaokao',
    url: 'https://raw.githubusercontent.com/KyleBing/english-vocabulary/master/%E9%AB%98%E4%B8%AD-%E9%A1%BA%E5%BA%8F.json',
    label: 'gaokao',
    topics: ['examination', 'high_school'],
  },
  {
    key: 'postgraduate',
    url: 'https://raw.githubusercontent.com/KyleBing/english-vocabulary/master/%E8%80%83%E7%A0%94-%E9%A1%BA%E5%BA%8F.json',
    label: 'postgraduate',
    topics: ['examination', 'advanced'],
  },
  {
    key: 'professional',
    url: 'https://raw.githubusercontent.com/KyleBing/english-vocabulary/master/SAT-%E9%A1%BA%E5%BA%8F.json',
    label: 'professional',
    topics: ['professional', 'academic'],
  },
];

interface KyleBingEntry {
  word: string;
  translations: { translation: string; type: string }[];
  phrases: { phrase: string; translation: string }[];
}

function cleanPhonetic(entry: KyleBingEntry): string {
  // KyleBing doesn't include phonetic — leave empty
  return '';
}

function buildPos(entry: KyleBingEntry): string {
  const types = new Set<string>();
  for (const t of entry.translations) {
    if (t.type) types.add(t.type.trim().toLowerCase());
  }
  if (types.size === 0) return 'n';
  return [...types].join('/');
}

function buildMeaning(entry: KyleBingEntry): string {
  return entry.translations
    .map((t) => t.translation.trim())
    .filter(Boolean)
    .join('；');
}

function buildCollocations(entry: KyleBingEntry): string[] {
  return entry.phrases.map((p) => p.phrase.trim()).filter(Boolean);
}

function buildExamples(entry: KyleBingEntry): { en: string; zh: string }[] {
  // Use first 2 phrases as example sentences
  return entry.phrases.slice(0, 2).map((p) => ({
    en: p.phrase.trim(),
    zh: p.translation.trim(),
  }));
}

async function main() {
  for (const src of SOURCES) {
    console.log(`Fetching ${src.key} from ${src.url}...`);
    const resp = await fetch(src.url);
    if (!resp.ok) {
      console.error(`  FAILED: HTTP ${resp.status} — skipping ${src.key}`);
      continue;
    }
    const raw: KyleBingEntry[] = await resp.json();
    console.log(`  Got ${raw.length} entries`);

    const labelUpper = src.key.toUpperCase();
    const lines: string[] = [];
    lines.push(`// ${src.label} wordbank — ${raw.length} words`);
    lines.push(`// Data source: KyleBing/english-vocabulary (MIT license)`);
    lines.push(`// Generated by scripts/generate-wordbank.ts`);
    lines.push(`import type { IWordEntry } from '../schema';`);
    lines.push(``);
    lines.push(`export const ${labelUpper}_WORDS: IWordEntry[] = [`);

    for (let i = 0; i < raw.length; i++) {
      const e = raw[i];
      const word = e.word.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
      const pos = buildPos(e).replace(/'/g, "\\'");
      const meaning = buildMeaning(e).replace(/'/g, "\\'");
      const phonetic = cleanPhonetic(e);
      const collocations = JSON.stringify(buildCollocations(e));
      const examples = JSON.stringify(buildExamples(e));

      lines.push(
        `  {word:'${word}',phonetic:'${phonetic}',partOfSpeech:'${pos}',meaning:'${meaning}',level:'${src.key}',frequencyRank:${i + 1},collocations:${collocations},examples:${examples},synonyms:[],antonyms:[],wordFamily:[],register:'neutral',emotion:'neutral',topics:${JSON.stringify(src.topics)},hasNoChineseEquivalent:false,deepExplanation:''},`
      );
    }

    lines.push(`];`);

    const outPath = path.join(DATA_DIR, `${src.key}.ts`);
    fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
    console.log(`  Written: ${outPath} (${(fs.statSync(outPath).size / 1024 / 1024).toFixed(1)} MB)`);
  }

  console.log('\nDone! Word counts for meta.ts:');
  for (const src of SOURCES) {
    const f = path.join(DATA_DIR, `${src.key}.ts`);
    if (fs.existsSync(f)) {
      const content = fs.readFileSync(f, 'utf-8');
      const count = (content.match(/level:'/g) || []).length;
      console.log(`  ${src.key}: ${count}`);
    }
  }
}

main().catch(console.error);
