// Generate chunks and vocabulary data files
import fs from 'fs';

// ============ CHUNKS ============
const chunks = [];
let cid = 0;
function addChunk(content, meaning, category, usage, example, difficulty) {
  cid++;
  chunks.push({ id: `c${cid}`, content, meaning, category, usage, example, difficulty });
}

// DAILY - 50
addChunk("hit the hay","上床睡觉","daily","非正式表示去睡觉","I'm exhausted, I'm gonna hit the hay early tonight.","intermediate");
addChunk("piece of cake","小菜一碟","daily","非常容易的事","The exam was a piece of cake I finished in 20 minutes.","beginner");
addChunk("out of the blue","突然地","daily","毫无征兆","He called me out of the blue after ten years.","intermediate");
addChunk("hit the spot","恰到好处","daily","食物让人满足","This ice cream really hits the spot on a hot day.","intermediate");
addChunk("no big deal","没什么大不了","daily","轻描淡写","Don't worry about it, it's no big deal.","beginner");
addChunk("give it a shot","试一试","daily","鼓励尝试","I've never tried yoga before but I'll give it a shot.","beginner");
addChunk("under the weather","身体不舒服","daily","委婉说生病","I'm feeling a bit under the weather today.","beginner");
addChunk("bite the bullet","硬着头皮","daily","做不情愿的事","I hate going to the dentist but I just have to bite the bullet.","intermediate");
addChunk("hit the books","用功学习","daily","开始学习","Finals are next week time to hit the books.","beginner");
addChunk("sit tight","耐心等待","daily","别着急","Sit tight the doctor will see you in a few minutes.","beginner");
addChunk("make ends meet","收支平衡","daily","勉强维生","With rising rent many families struggle to make ends meet.","intermediate");
addChunk("play it by ear","见机行事","daily","灵活应对","I'm not sure what time we'll finish let's just play it by ear.","intermediate");
addChunk("face the music","承担后果","daily","面对惩罚","You made the mistake now you have to face the music.","intermediate");
addChunk("call it a day","收工","daily","结束当天工作","It's 6pm let's call it a day and continue tomorrow.","beginner");
addChunk("hang in there","坚持住","daily","鼓励他人","I know training is tough but hang in there.","beginner");
addChunk("sleep on it","考虑一晚","daily","不急于决定","Don't decide now sleep on it and let me know tomorrow.","beginner");
addChunk("call the shots","做主说了算","daily","做决定的人","You're the boss you call the shots around here.","intermediate");
addChunk("cut corners","偷工减料","daily","降低质量","If you cut corners on safety someone is going to get hurt.","intermediate");
addChunk("draw the line","划清界限","daily","设定底线","I draw the line at working on weekends.","intermediate");
addChunk("go the extra mile","付出额外努力","daily","做得更多","She always goes the extra mile to help her clients.","intermediate");
addChunk("in a nutshell","简而言之","daily","概括复杂内容","In a nutshell the project was a huge success.","beginner");
addChunk("keep an eye on","留意照看","daily","注意某人某事","Can you keep an eye on the kids while I run to the store.","beginner");
addChunk("let the cat out of the bag","泄露秘密","daily","不小心说漏嘴","She let the cat out of the bag about the surprise party.","intermediate");
addChunk("miss the boat","错过机会","daily","没赶上","I waited too long and missed the boat on that job.","intermediate");
addChunk("once in a blue moon","千载难逢","daily","极为罕见","He calls his parents once in a blue moon.","intermediate");
addChunk("pull yourself together","振作起来","daily","冷静下来","Pull yourself together we still have work to do.","intermediate");
addChunk("ring a bell","听起来熟悉","daily","模糊记得","His name rings a bell but I can't remember where.","beginner");
addChunk("screw up","搞砸","daily","犯大错","I really screwed up that presentation everyone was confused.","beginner");
addChunk("take it easy","放轻松","daily","别紧张","Take it easy stress is bad for your health.","beginner");
addChunk("up to speed","了解最新情况","daily","跟上进度","Let me bring you up to speed on what's happened.","intermediate");
addChunk("a blessing in disguise","因祸得福","daily","坏事变好事","Losing that job was a blessing in disguise.","advanced");
addChunk("back to square one","回到原点","daily","重新开始","The deal fell through so we're back to square one.","intermediate");
addChunk("cross that bridge","船到桥头自然直","daily","不必过早担忧","Don't stress cross that bridge when you come to it.","advanced");
addChunk("cut to the chase","切入正题","daily","直接说重点","We don't have much time so let me cut to the chase.","intermediate");
addChunk("every cloud has a silver lining","黑暗中总有一线光明","daily","坏事有好的一面","I know you're upset but every cloud has a silver lining.","advanced");
addChunk("hit the nail on the head","一针见血","daily","说到点子上","You hit the nail on the head that's exactly the problem.","intermediate");
addChunk("it takes two to tango","一个巴掌拍不响","daily","双方都有责任","Don't blame just him it takes two to tango.","intermediate");
addChunk("kill two birds with one stone","一举两得","daily","一次做两件事","I kill two birds with one stone by biking to work.","intermediate");
addChunk("make a long story short","长话短说","daily","概括叙述","To make a long story short we missed our flight.","beginner");
addChunk("nip it in the bud","防患于未然","daily","及早制止","We need to nip this issue in the bud before it gets worse.","advanced");
addChunk("off the top of my head","随口一说","daily","不假思索","Off the top of my head I'd say about 200 showed up.","intermediate");
addChunk("stick to your guns","坚持立场","daily","不因压力改变","Don't let them change your mind stick to your guns.","intermediate");
addChunk("the ball is in your court","轮到你了","daily","由你决定","I've done my part now the ball is in your court.","intermediate");
addChunk("you can say that again","你说得太对了","daily","强烈赞同","A: Traffic is terrible. B: You can say that again!","beginner");
addChunk("a dime a dozen","随处可见","daily","极其常见","Good ideas are a dime a dozen execution is what matters.","intermediate");
addChunk("back to basics","回归根本","daily","从基础开始","We need to get back to basics with our training.","beginner");
addChunk("better late than never","迟做总比不做好","daily","鼓励补做","I finally finished my taxes better late than never.","beginner");
addChunk("down to earth","脚踏实地","daily","务实不浮夸","Despite his fame he's very down to earth.","intermediate");
addChunk("from scratch","从头开始","daily","从零做起","She baked the cake from scratch no box mix.","intermediate");
addChunk("get over it","克服放下","daily","不再纠结","It happened years ago get over it already.","beginner");

// WORKPLACE - 50
addChunk("get the ball rolling","开始行动","workplace","启动项目","Let's get the ball rolling on this project by Friday.","intermediate");
addChunk("touch base","联系碰头","workplace","简短沟通","Let's touch base next week about the project status.","beginner");
addChunk("on the same page","意见一致","workplace","确认共识","Let's make sure everyone is on the same page before we proceed.","beginner");
addChunk("think outside the box","创新思考","workplace","创造性解决问题","We need to think outside the box to solve this challenge.","intermediate");
addChunk("rule of thumb","经验法则","workplace","通用规则","As a rule of thumb save 20 percent of your income.","advanced");
addChunk("up in the air","悬而未决","workplace","计划未定","Our travel plans are still up in the air.","intermediate");
addChunk("ahead of the curve","领先一步","workplace","比同行超前","Our R and D team stays ahead of the curve on new tech.","advanced");
addChunk("back to the drawing board","从头再来","workplace","方案被否","The client rejected it back to the drawing board.","intermediate");
addChunk("bottom line","最终结果","workplace","最重要的一点","The bottom line is we need to increase sales.","intermediate");
addChunk("by the book","照章办事","workplace","严格按规定","Our accountant does everything by the book.","beginner");
addChunk("come up short","未达预期","workplace","差一点完成","We came up short on our quarterly targets.","intermediate");
addChunk("cutting edge","尖端前沿","workplace","技术领先","Their lab does cutting edge research.","intermediate");
addChunk("game changer","改变游戏规则","workplace","颠覆性创新","This new tech could be a real game changer.","intermediate");
addChunk("get down to business","开始谈正事","workplace","正式进入主题","Alright everyone let's get down to business.","beginner");
addChunk("hit the ground running","快速上手","workplace","新人迅速进入状态","We need someone who can hit the ground running.","intermediate");
addChunk("in the loop","知情的","workplace","了解最新情况","Please keep me in the loop on major decisions.","beginner");
addChunk("learn the ropes","熟悉工作","workplace","新人学习业务","It took a month to really learn the ropes here.","intermediate");
addChunk("on the back burner","搁置中","workplace","暂时不处理","Let's put this on the back burner for now.","intermediate");
addChunk("raise the bar","提高标准","workplace","设定更高目标","Our competitors have really raised the bar.","intermediate");
addChunk("see eye to eye","看法一致","workplace","意见相同","My manager and I don't always see eye to eye.","beginner");
addChunk("take the bull by the horns","迎难而上","workplace","勇敢面对","Someone needs to take the bull by the horns.","advanced");
addChunk("throw in the towel","放弃","workplace","不再努力","After three failed attempts they threw in the towel.","intermediate");
addChunk("win-win situation","双赢局面","workplace","对双方有利","The partnership is a win-win for both companies.","beginner");
addChunk("word of mouth","口碑传播","workplace","靠推介","Most of our business comes through word of mouth.","beginner");
addChunk("read between the lines","读懂言外之意","workplace","理解隐藏意思","Reading between the lines I think they'll cancel.","intermediate");
addChunk("the elephant in the room","显而易见的问题","workplace","被回避的话题","Let's address the elephant in the room the budget cut.","advanced");
addChunk("walk the talk","说到做到","workplace","言行一致","We need leaders who walk the talk not just make promises.","intermediate");
addChunk("water under the bridge","过去的事了","workplace","不再纠结","That disagreement is water under the bridge.","intermediate");
addChunk("put out fires","紧急救火","workplace","处理紧急问题","I spent all day putting out fires.","intermediate");
addChunk("move the needle","产生显著影响","workplace","有明显效果","We need a campaign that really moves the needle.","advanced");
addChunk("circle back","回头再谈","workplace","稍后讨论","Let's circle back to this after lunch.","beginner");
addChunk("low-hanging fruit","容易实现的目标","workplace","轻易可得","Let's tackle the low-hanging fruit first.","intermediate");
addChunk("drill down","深入分析","workplace","仔细研究","We need to drill down into the data.","intermediate");
addChunk("take ownership","承担责任","workplace","对结果负责","I want you to take ownership of this project.","intermediate");
addChunk("shift gears","转换方向","workplace","改变策略","After the market changed we had to shift gears.","intermediate");
addChunk("bandwidth","精力时间","workplace","有空做某事","I don't have the bandwidth for another project.","intermediate");
addChunk("deep dive","深入探讨","workplace","仔细研究","Let's do a deep dive into the user feedback.","intermediate");
addChunk("push the envelope","突破界限","workplace","挑战极限","Our design team always pushes the envelope.","advanced");
addChunk("streamline","精简流程","workplace","优化效率","We're streamlining our onboarding process.","intermediate");
addChunk("get the lay of the land","了解情况","workplace","熟悉新环境","Get the lay of the land before proposing changes.","intermediate");
addChunk("pain point","痛点","workplace","用户困难之处","What are the biggest pain points for our users.","intermediate");
addChunk("buy-in","认可接受","workplace","真心支持和投入","We need buy-in from the leadership team.","intermediate");
addChunk("fast track","快速通道","workplace","加快进程","She was put on the fast track to management.","intermediate");
addChunk("take the reins","接管领导","workplace","接手掌管","When the CEO retired she took the reins.","advanced");
addChunk("pivot","转型转向","workplace","改变核心业务","The startup pivoted from B2C to B2B.","intermediate");
addChunk("traction","吸引力势头","workplace","被越来越多人接受","Our product is finally gaining traction.","intermediate");
addChunk("ramp up","加大力度","workplace","快速提升","We need to ramp up production before the holidays.","intermediate");
addChunk("synergy","协同效应","workplace","一加一大于二","The merger should create significant synergies.","advanced");
addChunk("deliverable","交付物","workplace","可交付成果","What are the key deliverables for this quarter.","intermediate");
addChunk("stakeholder","利益相关方","workplace","有利害关系的人","We need approval from all stakeholders.","intermediate");

// SOCIAL - 50
addChunk("Long time no see","好久不见","social","熟人重逢","Hey Tom long time no see How have you been.","beginner");
addChunk("break the ice","打破沉默","social","缓解紧张","He told a joke to break the ice at the meeting.","beginner");
addChunk("spill the beans","泄露秘密","social","说出秘密","Come on spill the beans What did he say.","intermediate");
addChunk("rain check","改天再说","social","婉拒邀约","I can't make dinner tonight can I take a rain check.","intermediate");
addChunk("beat around the bush","拐弯抹角","social","不直说","Stop beating around the bush and tell me the truth.","intermediate");
addChunk("blow off steam","发泄情绪","social","释放压力","I need to blow off some steam this weekend.","intermediate");
addChunk("break a leg","祝好运","social","演出前祝福","You'll do great break a leg.","beginner");
addChunk("chip in","凑份子","social","大家出钱","If we all chip in we can buy her a nice gift.","beginner");
addChunk("cut someone some slack","宽容一点","social","不要苛刻","Cut him some slack he's only been here a week.","intermediate");
addChunk("drop someone a line","发消息联系","social","保持联系","Drop me a line when you get to London.","beginner");
addChunk("get out of hand","失控","social","局面失控","The party got out of hand after midnight.","intermediate");
addChunk("give the cold shoulder","冷落","social","故意不理","She's been giving me the cold shoulder since the meeting.","intermediate");
addChunk("go Dutch","AA制","social","各付各的","Let's go Dutch on dinner tonight.","beginner");
addChunk("hang out","一起玩","social","非正式相聚","We're just hanging out at my place want to come over.","beginner");
addChunk("hit it off","一拍即合","social","刚认识就投缘","We met at the conference and really hit it off.","intermediate");
addChunk("keep in touch","保持联系","social","分别时客套","It was great meeting you let's keep in touch.","beginner");
addChunk("paint the town red","狂欢庆祝","social","大肆庆祝","After the promotion we painted the town red.","intermediate");
addChunk("pull someone's leg","开玩笑","social","善意骗人","Don't believe him he's just pulling your leg.","intermediate");
addChunk("steal someone's thunder","抢风头","social","夺走注意力","Don't announce your news at her wedding.","intermediate");
addChunk("the more the merrier","人越多越热闹","social","欢迎更多人","Can I bring my cousin Sure the more the merrier.","beginner");
addChunk("wine and dine","盛情款待","social","高档招待","The company wined and dined the investors.","intermediate");
addChunk("two peas in a pod","形影不离","social","两人极相似","Those two are like two peas in a pod.","intermediate");
addChunk("rub the wrong way","惹恼","social","让人不爽","His tone rubbed me the wrong way.","intermediate");
addChunk("have a bone to pick","找某人算账","social","有不满要说","I've got a bone to pick with you about yesterday.","advanced");
addChunk("clear the air","消除误会","social","坦诚沟通","We had a good talk and cleared the air.","intermediate");
addChunk("bury the hatchet","和解","social","结束分歧","After years of rivalry they finally buried the hatchet.","advanced");
addChunk("a shoulder to cry on","倾诉对象","social","安慰你的人","She was a shoulder to cry on during the breakup.","intermediate");
addChunk("make yourself at home","随意一点","social","让客人放松","Come on in Make yourself at home.","beginner");
addChunk("no hard feelings","不计前嫌","social","表示不记恨","I hope there's no hard feelings after our debate.","intermediate");
addChunk("pick someone's brain","请教","social","征求意见","Can I pick your brain about the project.","intermediate");
addChunk("put your foot in your mouth","说错话","social","无心说尴尬话","I put my foot in my mouth when I asked about her ex.","intermediate");
addChunk("stand someone up","放鸽子","social","约会爽约","I waited for an hour but she stood me up.","beginner");
addChunk("sweep under the rug","掩盖问题","social","隐藏不愉快","You can't just sweep this under the rug.","advanced");
addChunk("tag along","跟着去","social","加入别人","We're going to the mall want to tag along.","beginner");
addChunk("talk shop","谈论工作","social","社交场合谈公事","No talking shop at dinner please.","intermediate");
addChunk("wrap up","结束","social","收尾","Let's wrap up the meeting we've covered everything.","beginner");
addChunk("get-together","聚会","social","非正式聚会","We're having a small get-together on Saturday.","beginner");
addChunk("small talk","寒暄闲聊","social","轻松闲聊","We made some small talk before the meeting.","beginner");
addChunk("social butterfly","社交达人","social","会社交的人","She's such a social butterfly she knows everyone.","intermediate");
addChunk("party pooper","扫兴的人","social","破坏气氛","Don't be a party pooper come out with us.","intermediate");
addChunk("people pleaser","讨好别人的人","social","总想让所有人满意","Stop being a people pleaser stand up for yourself.","intermediate");
addChunk("icebreaker","破冰活动","social","帮陌生人认识","We started with a quick icebreaker game.","intermediate");
addChunk("catch up","叙旧","social","了解近况","It's been ages We should grab lunch and catch up.","beginner");
addChunk("lend a hand","帮忙","social","伸出援手","Can you lend me a hand with these boxes.","beginner");
addChunk("hit the town","出去玩","social","逛街吃饭娱乐","It's Friday let's hit the town.","beginner");
addChunk("patch things up","修复关系","social","和好","They had a fight but patched things up next day.","intermediate");
addChunk("open up","敞开心扉","social","坦诚分享","It took him years to finally open up about his past.","intermediate");
addChunk("bond over","因之建立感情","social","通过共同兴趣建立关系","We bonded over our shared love of hiking.","intermediate");
addChunk("show the ropes","教人入门","social","指导新人","Let me show you the ropes around the office.","intermediate");
addChunk("feel left out","被冷落","social","感到被排斥","Everyone was laughing but I felt left out.","intermediate");

// EMOTION - 50
addChunk("on cloud nine","欣喜若狂","emotion","极度高兴","She was on cloud nine after getting the promotion.","intermediate");
addChunk("over the moon","乐翻了","emotion","极度开心","She was over the moon about the acceptance letter.","beginner");
addChunk("get cold feet","临阵退缩","emotion","做事前害怕","He got cold feet right before the wedding.","intermediate");
addChunk("bored to tears","无聊透了","emotion","极度无聊","The lecture was so dull I was bored to tears.","intermediate");
addChunk("butterflies in stomach","七上八下","emotion","紧张不安","I always get butterflies before a big presentation.","intermediate");
addChunk("down in the dumps","情绪低落","emotion","心情不好","He's been down in the dumps since his team lost.","intermediate");
addChunk("drive someone up the wall","把人逼疯","emotion","极度烦人","That noise is driving me up the wall.","intermediate");
addChunk("fed up","受够了","emotion","忍无可忍","I'm fed up with all the office politics.","beginner");
addChunk("freak out","吓坏了","emotion","极度恐慌","My mom is going to freak out when she sees this.","beginner");
addChunk("get on someone's nerves","惹人心烦","emotion","持续烦躁","His humming really gets on my nerves.","intermediate");
addChunk("give someone the creeps","毛骨悚然","emotion","让人不舒服","That abandoned house gives me the creeps.","intermediate");
addChunk("green with envy","非常嫉妒","emotion","极度羡慕","She was green with envy when she saw my new car.","intermediate");
addChunk("have a blast","玩得超开心","emotion","愉快时光","We had a blast at the concert last night.","beginner");
addChunk("hit rock bottom","跌入谷底","emotion","人生最低点","After losing his job and home he hit rock bottom.","advanced");
addChunk("keep your chin up","别气馁","emotion","鼓舞士气","Keep your chin up things will get better.","intermediate");
addChunk("like a fish out of water","格格不入","emotion","陌生环境不自在","At the formal gala I felt like a fish out of water.","intermediate");
addChunk("make my blood boil","火冒三丈","emotion","极度愤怒","Seeing people litter makes my blood boil.","intermediate");
addChunk("on pins and needles","如坐针毡","emotion","焦虑等待","We were on pins and needles waiting for results.","intermediate");
addChunk("over the top","太夸张了","emotion","行为夸张","The wedding decorations were a bit over the top.","beginner");
addChunk("rub it in","伤口上撒盐","emotion","反复提醒失败","OK I messed up you don't have to rub it in.","intermediate");
addChunk("scared stiff","吓呆了","emotion","极度害怕","I was scared stiff when I heard footsteps.","intermediate");
addChunk("sick and tired","厌烦透了","emotion","长期厌倦","I'm sick and tired of their complaining.","beginner");
addChunk("thrilled to bits","开心极了","emotion","非常兴奋","She was thrilled to bits when she won the award.","beginner");
addChunk("tongue-tied","张口结舌","emotion","紧张说不出话","I got tongue-tied when she asked about my feelings.","intermediate");
addChunk("torn between","左右为难","emotion","两个选择间纠结","I'm torn between the job offer and staying in school.","intermediate");
addChunk("walk on eggshells","小心翼翼","emotion","怕惹人生气","I've been walking on eggshells around him.","intermediate");
addChunk("wear your heart on your sleeve","喜怒形于色","emotion","情感外露","She wears her heart on her sleeve.","advanced");
addChunk("weep with joy","喜极而泣","emotion","开心到哭","She wept with joy when her son returned safely.","beginner");
addChunk("blow a fuse","大发雷霆","emotion","突然非常生气","Dad blew a fuse when he saw the dent in his car.","intermediate");
addChunk("chip on your shoulder","心怀不满","emotion","因过去经历敏感","He's had a chip on his shoulder since being passed over.","advanced");
addChunk("cry over spilled milk","纠结无法改变的事","emotion","为打翻的牛奶哭泣","There's no use crying over spilled milk.","beginner");
addChunk("grin and bear it","咬牙忍受","emotion","忍住不快","I hate these meetings but I just grin and bear it.","intermediate");
addChunk("in seventh heaven","极乐世界","emotion","极度幸福","After the proposal she was in seventh heaven.","intermediate");
addChunk("jump for joy","高兴得跳起来","emotion","非常兴奋","The kids jumped for joy when they saw the puppy.","beginner");
addChunk("lose your cool","失去冷静","emotion","情绪失控","He rarely loses his cool but this time he was furious.","intermediate");
addChunk("mixed feelings","复杂的感受","emotion","又喜又悲","I have mixed feelings about moving to a new city.","beginner");
addChunk("nerves of steel","钢铁意志","emotion","非常冷静","You need nerves of steel to be an air traffic controller.","intermediate");
addChunk("on edge","紧张不安","emotion","焦虑警惕","The city has been on edge since the warning.","intermediate");
addChunk("sour grapes","酸葡萄心理","emotion","得不到就说不好","His criticism is just sour grapes he never entered.","advanced");
addChunk("take to heart","往心里去","emotion","过于认真对待批评","Don't take his comments to heart.","intermediate");
addChunk("thick-skinned","厚脸皮","emotion","不在乎批评","You need to be thick-skinned in customer service.","intermediate");
addChunk("thin-skinned","敏感的","emotion","容易受伤","He's too thin-skinned to handle negative feedback.","intermediate");
addChunk("turn a blind eye","视而不见","emotion","假装没看见","The manager turned a blind eye to the violations.","intermediate");
addChunk("vent frustration","发泄情绪","emotion","释放负面情绪","Going for a run helps me vent my frustration.","intermediate");
addChunk("at the end of your rope","山穷水尽","emotion","耐心耗尽","I'm at the end of my rope with this project.","advanced");
addChunk("bent out of shape","非常生气","emotion","因小事过于恼怒","Don't get all bent out of shape over a minor mistake.","intermediate");
addChunk("counting blessings","感恩知足","emotion","逆境中想好的方面","After the accident we started counting our blessings.","intermediate");
addChunk("bottle up feelings","压抑感情","emotion","不表达内心情感","Don't bottle up your feelings talk to someone.","intermediate");
addChunk("calm before the storm","暴风雨前的平静","emotion","大事前的平静","The office was quiet calm before the storm.","intermediate");
addChunk("heartwarming","暖心","emotion","让人心里一暖","The reunion video was absolutely heartwarming.","intermediate");

// Build TS
let esc = (s) => s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
let ts = "// EXPORTS: IChunk, MOCK_CHUNKS\n";
ts += "export interface IChunk {\n";
ts += "  id: string; content: string; meaning: string;\n";
ts += "  category: 'daily' | 'workplace' | 'social' | 'emotion';\n";
ts += "  usage: string; example: string;\n";
ts += "  difficulty: 'beginner' | 'intermediate' | 'advanced';\n";
ts += "}\n\n";
ts += "export const MOCK_CHUNKS: IChunk[] = [\n";
for (const c of chunks) {
  ts += `  { id:'${c.id}', content:'${esc(c.content)}', meaning:'${esc(c.meaning)}', category:'${c.category}', usage:'${esc(c.usage)}', example:'${esc(c.example)}', difficulty:'${c.difficulty}' },\n`;
}
ts += "];\n";
fs.writeFileSync("src/data/chunks.ts", ts);
console.log("Written " + chunks.length + " chunks to chunks.ts");
